// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calendar.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllJewishEvents = `-- name: GetAllJewishEvents :many


SELECT
    je.id,
    je.code,
    je.name_hebrew,
    je.name_english,
    jet.key as event_type,
    je.duration_days_israel,
    je.duration_days_diaspora,
    fst.key as fast_start_type,
    parent_je.code as parent_event_code,
    je.sort_order
FROM jewish_events je
LEFT JOIN jewish_event_types jet ON je.event_type_id = jet.id
LEFT JOIN fast_start_types fst ON je.fast_start_type_id = fst.id
LEFT JOIN jewish_events parent_je ON je.parent_event_id = parent_je.id
ORDER BY je.sort_order, je.name_english
`

type GetAllJewishEventsRow struct {
	ID                   int32   `json:"id"`
	Code                 string  `json:"code"`
	NameHebrew           string  `json:"name_hebrew"`
	NameEnglish          string  `json:"name_english"`
	EventType            *string `json:"event_type"`
	DurationDaysIsrael   *int32  `json:"duration_days_israel"`
	DurationDaysDiaspora *int32  `json:"duration_days_diaspora"`
	FastStartType        *string `json:"fast_start_type"`
	ParentEventCode      *string `json:"parent_event_code"`
	SortOrder            *int32  `json:"sort_order"`
}

// Calendar and Jewish Events SQL Queries
// SQLc will generate type-safe Go code from these queries
// ============================================
// JEWISH EVENTS QUERIES
// ============================================
// Get all Jewish events with their type information
func (q *Queries) GetAllJewishEvents(ctx context.Context) ([]GetAllJewishEventsRow, error) {
	rows, err := q.db.Query(ctx, getAllJewishEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllJewishEventsRow{}
	for rows.Next() {
		var i GetAllJewishEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.NameHebrew,
			&i.NameEnglish,
			&i.EventType,
			&i.DurationDaysIsrael,
			&i.DurationDaysDiaspora,
			&i.FastStartType,
			&i.ParentEventCode,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJewishEventsByType = `-- name: GetJewishEventsByType :many
SELECT
    je.id,
    je.code,
    je.name_hebrew,
    je.name_english,
    jet.key as event_type,
    je.duration_days_israel,
    je.duration_days_diaspora,
    fst.key as fast_start_type,
    parent_je.code as parent_event_code,
    je.sort_order
FROM jewish_events je
LEFT JOIN jewish_event_types jet ON je.event_type_id = jet.id
LEFT JOIN fast_start_types fst ON je.fast_start_type_id = fst.id
LEFT JOIN jewish_events parent_je ON je.parent_event_id = parent_je.id
WHERE jet.key = $1
ORDER BY je.sort_order, je.name_english
`

type GetJewishEventsByTypeRow struct {
	ID                   int32   `json:"id"`
	Code                 string  `json:"code"`
	NameHebrew           string  `json:"name_hebrew"`
	NameEnglish          string  `json:"name_english"`
	EventType            *string `json:"event_type"`
	DurationDaysIsrael   *int32  `json:"duration_days_israel"`
	DurationDaysDiaspora *int32  `json:"duration_days_diaspora"`
	FastStartType        *string `json:"fast_start_type"`
	ParentEventCode      *string `json:"parent_event_code"`
	SortOrder            *int32  `json:"sort_order"`
}

// Get Jewish events filtered by event type
func (q *Queries) GetJewishEventsByType(ctx context.Context, key string) ([]GetJewishEventsByTypeRow, error) {
	rows, err := q.db.Query(ctx, getJewishEventsByType, key)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetJewishEventsByTypeRow{}
	for rows.Next() {
		var i GetJewishEventsByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.NameHebrew,
			&i.NameEnglish,
			&i.EventType,
			&i.DurationDaysIsrael,
			&i.DurationDaysDiaspora,
			&i.FastStartType,
			&i.ParentEventCode,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMasterZmanimByEvent = `-- name: GetMasterZmanimByEvent :many

SELECT DISTINCT
    mr.id,
    mr.zman_key,
    mr.canonical_hebrew_name,
    mr.canonical_english_name,
    mr.transliteration,
    mr.description,
    mr.halachic_notes,
    mr.halachic_source,
    tc.key as time_category,
    mr.default_formula_dsl,
    mr.is_core,
    mr.created_at,
    mr.updated_at
FROM master_zmanim_registry mr
LEFT JOIN time_categories tc ON mr.time_category_id = tc.id
JOIN master_zman_events mze ON mr.id = mze.master_zman_id
JOIN jewish_events je ON je.id = mze.jewish_event_id
WHERE je.code = $1 AND mze.is_primary = true
ORDER BY tc.sort_order, mr.canonical_hebrew_name
`

type GetMasterZmanimByEventRow struct {
	ID                   int32              `json:"id"`
	ZmanKey              string             `json:"zman_key"`
	CanonicalHebrewName  string             `json:"canonical_hebrew_name"`
	CanonicalEnglishName string             `json:"canonical_english_name"`
	Transliteration      *string            `json:"transliteration"`
	Description          *string            `json:"description"`
	HalachicNotes        *string            `json:"halachic_notes"`
	HalachicSource       *string            `json:"halachic_source"`
	TimeCategory         *string            `json:"time_category"`
	DefaultFormulaDsl    *string            `json:"default_formula_dsl"`
	IsCore               *bool              `json:"is_core"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

// ============================================
// MASTER ZMANIM BY EVENT QUERIES
// ============================================
// Get all master zmanim associated with a specific Jewish event
func (q *Queries) GetMasterZmanimByEvent(ctx context.Context, code string) ([]GetMasterZmanimByEventRow, error) {
	rows, err := q.db.Query(ctx, getMasterZmanimByEvent, code)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMasterZmanimByEventRow{}
	for rows.Next() {
		var i GetMasterZmanimByEventRow
		if err := rows.Scan(
			&i.ID,
			&i.ZmanKey,
			&i.CanonicalHebrewName,
			&i.CanonicalEnglishName,
			&i.Transliteration,
			&i.Description,
			&i.HalachicNotes,
			&i.HalachicSource,
			&i.TimeCategory,
			&i.DefaultFormulaDsl,
			&i.IsCore,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMasterZmanimByEventAndDay = `-- name: GetMasterZmanimByEventAndDay :many
SELECT DISTINCT
    mr.id,
    mr.zman_key,
    mr.canonical_hebrew_name,
    mr.canonical_english_name,
    mr.transliteration,
    mr.description,
    mr.halachic_notes,
    mr.halachic_source,
    tc.key as time_category,
    mr.default_formula_dsl,
    mr.is_core,
    mr.created_at,
    mr.updated_at
FROM master_zmanim_registry mr
LEFT JOIN time_categories tc ON mr.time_category_id = tc.id
JOIN master_zman_events mze ON mr.id = mze.master_zman_id
JOIN jewish_events je ON je.id = mze.jewish_event_id
WHERE je.code = $1 AND mze.is_primary = true
ORDER BY tc.sort_order, mr.canonical_hebrew_name
`

type GetMasterZmanimByEventAndDayRow struct {
	ID                   int32              `json:"id"`
	ZmanKey              string             `json:"zman_key"`
	CanonicalHebrewName  string             `json:"canonical_hebrew_name"`
	CanonicalEnglishName string             `json:"canonical_english_name"`
	Transliteration      *string            `json:"transliteration"`
	Description          *string            `json:"description"`
	HalachicNotes        *string            `json:"halachic_notes"`
	HalachicSource       *string            `json:"halachic_source"`
	TimeCategory         *string            `json:"time_category"`
	DefaultFormulaDsl    *string            `json:"default_formula_dsl"`
	IsCore               *bool              `json:"is_core"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

// Get master zmanim for a specific event (all days, no day filtering in DB)
// Note: The original code had applies_to_day column which doesn't exist in schema
// This query returns all zmanim for the event; day filtering should be done in application layer
func (q *Queries) GetMasterZmanimByEventAndDay(ctx context.Context, code string) ([]GetMasterZmanimByEventAndDayRow, error) {
	rows, err := q.db.Query(ctx, getMasterZmanimByEventAndDay, code)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMasterZmanimByEventAndDayRow{}
	for rows.Next() {
		var i GetMasterZmanimByEventAndDayRow
		if err := rows.Scan(
			&i.ID,
			&i.ZmanKey,
			&i.CanonicalHebrewName,
			&i.CanonicalEnglishName,
			&i.Transliteration,
			&i.Description,
			&i.HalachicNotes,
			&i.HalachicSource,
			&i.TimeCategory,
			&i.DefaultFormulaDsl,
			&i.IsCore,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getZmanApplicableEvents = `-- name: GetZmanApplicableEvents :many

SELECT
    je.id,
    je.code,
    je.name_hebrew,
    je.name_english,
    jet.key as event_type,
    je.duration_days_israel,
    je.duration_days_diaspora,
    fst.key as fast_start_type,
    parent_je.code as parent_event_code,
    je.sort_order,
    mze.is_primary,
    mze.override_hebrew_name,
    mze.override_english_name
FROM jewish_events je
LEFT JOIN jewish_event_types jet ON je.event_type_id = jet.id
LEFT JOIN fast_start_types fst ON je.fast_start_type_id = fst.id
LEFT JOIN jewish_events parent_je ON je.parent_event_id = parent_je.id
JOIN master_zman_events mze ON je.id = mze.jewish_event_id
JOIN master_zmanim_registry mr ON mr.id = mze.master_zman_id
WHERE mr.zman_key = $1
ORDER BY je.sort_order
`

type GetZmanApplicableEventsRow struct {
	ID                   int32   `json:"id"`
	Code                 string  `json:"code"`
	NameHebrew           string  `json:"name_hebrew"`
	NameEnglish          string  `json:"name_english"`
	EventType            *string `json:"event_type"`
	DurationDaysIsrael   *int32  `json:"duration_days_israel"`
	DurationDaysDiaspora *int32  `json:"duration_days_diaspora"`
	FastStartType        *string `json:"fast_start_type"`
	ParentEventCode      *string `json:"parent_event_code"`
	SortOrder            *int32  `json:"sort_order"`
	IsPrimary            *bool   `json:"is_primary"`
	OverrideHebrewName   *string `json:"override_hebrew_name"`
	OverrideEnglishName  *string `json:"override_english_name"`
}

// ============================================
// ZMAN APPLICABLE EVENTS QUERIES
// ============================================
// Get all Jewish events that a specific zman applies to
func (q *Queries) GetZmanApplicableEvents(ctx context.Context, zmanKey string) ([]GetZmanApplicableEventsRow, error) {
	rows, err := q.db.Query(ctx, getZmanApplicableEvents, zmanKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetZmanApplicableEventsRow{}
	for rows.Next() {
		var i GetZmanApplicableEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.NameHebrew,
			&i.NameEnglish,
			&i.EventType,
			&i.DurationDaysIsrael,
			&i.DurationDaysDiaspora,
			&i.FastStartType,
			&i.ParentEventCode,
			&i.SortOrder,
			&i.IsPrimary,
			&i.OverrideHebrewName,
			&i.OverrideEnglishName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getZmanDisplayContextsByKey = `-- name: GetZmanDisplayContextsByKey :many

SELECT
    zdc.id,
    zdc.context_code,
    zdc.display_name_hebrew,
    zdc.display_name_english,
    zdc.sort_order
FROM zman_display_contexts zdc
JOIN master_zmanim_registry mr ON mr.id = zdc.master_zman_id
WHERE mr.zman_key = $1
ORDER BY zdc.sort_order
`

type GetZmanDisplayContextsByKeyRow struct {
	ID                 int32  `json:"id"`
	ContextCode        string `json:"context_code"`
	DisplayNameHebrew  string `json:"display_name_hebrew"`
	DisplayNameEnglish string `json:"display_name_english"`
	SortOrder          *int32 `json:"sort_order"`
}

// ============================================
// ZMAN DISPLAY CONTEXTS QUERIES
// ============================================
// Get display contexts for a specific zman by zman_key
func (q *Queries) GetZmanDisplayContextsByKey(ctx context.Context, zmanKey string) ([]GetZmanDisplayContextsByKeyRow, error) {
	rows, err := q.db.Query(ctx, getZmanDisplayContextsByKey, zmanKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetZmanDisplayContextsByKeyRow{}
	for rows.Next() {
		var i GetZmanDisplayContextsByKeyRow
		if err := rows.Scan(
			&i.ID,
			&i.ContextCode,
			&i.DisplayNameHebrew,
			&i.DisplayNameEnglish,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
