// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: correction_requests.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminUpdateCity = `-- name: AdminUpdateCity :exec
UPDATE geo_cities
SET
  latitude = COALESCE($1::double precision, latitude),
  longitude = COALESCE($2::double precision, longitude),
  elevation_m = COALESCE($3::integer, elevation_m),
  updated_at = now()
WHERE id = $4::bigint
`

type AdminUpdateCityParams struct {
	Latitude  *float64 `json:"latitude"`
	Longitude *float64 `json:"longitude"`
	Elevation *int32   `json:"elevation"`
	ID        int64    `json:"id"`
}

func (q *Queries) AdminUpdateCity(ctx context.Context, arg AdminUpdateCityParams) error {
	_, err := q.db.Exec(ctx, adminUpdateCity,
		arg.Latitude,
		arg.Longitude,
		arg.Elevation,
		arg.ID,
	)
	return err
}

const applyCityCorrection = `-- name: ApplyCityCorrection :exec
UPDATE geo_cities
SET
  latitude = COALESCE($1::double precision, latitude),
  longitude = COALESCE($2::double precision, longitude),
  elevation_m = COALESCE($3::integer, elevation_m),
  updated_at = now()
WHERE id = $4::bigint
`

type ApplyCityCorrectionParams struct {
	ProposedLatitude  *float64 `json:"proposed_latitude"`
	ProposedLongitude *float64 `json:"proposed_longitude"`
	ProposedElevation *int32   `json:"proposed_elevation"`
	ID                int64    `json:"id"`
}

func (q *Queries) ApplyCityCorrection(ctx context.Context, arg ApplyCityCorrectionParams) error {
	_, err := q.db.Exec(ctx, applyCityCorrection,
		arg.ProposedLatitude,
		arg.ProposedLongitude,
		arg.ProposedElevation,
		arg.ID,
	)
	return err
}

const createCorrectionRequest = `-- name: CreateCorrectionRequest :one

INSERT INTO city_correction_requests (
  city_id,
  publisher_id,
  requester_email,
  requester_name,
  proposed_latitude,
  proposed_longitude,
  proposed_elevation,
  correction_reason,
  evidence_urls
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, city_id, publisher_id, requester_email, requester_name, proposed_latitude, proposed_longitude, proposed_elevation, correction_reason, evidence_urls, status, reviewed_by, reviewed_at, review_notes, created_at, updated_at
`

type CreateCorrectionRequestParams struct {
	CityID            int64    `json:"city_id"`
	PublisherID       *int32   `json:"publisher_id"`
	RequesterEmail    string   `json:"requester_email"`
	RequesterName     *string  `json:"requester_name"`
	ProposedLatitude  *float64 `json:"proposed_latitude"`
	ProposedLongitude *float64 `json:"proposed_longitude"`
	ProposedElevation *int32   `json:"proposed_elevation"`
	CorrectionReason  string   `json:"correction_reason"`
	EvidenceUrls      []string `json:"evidence_urls"`
}

// File: correction_requests.sql
// Purpose: SQLc queries for city correction requests
// Story: 6.5 - Public Correction Requests
func (q *Queries) CreateCorrectionRequest(ctx context.Context, arg CreateCorrectionRequestParams) (CityCorrectionRequest, error) {
	row := q.db.QueryRow(ctx, createCorrectionRequest,
		arg.CityID,
		arg.PublisherID,
		arg.RequesterEmail,
		arg.RequesterName,
		arg.ProposedLatitude,
		arg.ProposedLongitude,
		arg.ProposedElevation,
		arg.CorrectionReason,
		arg.EvidenceUrls,
	)
	var i CityCorrectionRequest
	err := row.Scan(
		&i.ID,
		&i.CityID,
		&i.PublisherID,
		&i.RequesterEmail,
		&i.RequesterName,
		&i.ProposedLatitude,
		&i.ProposedLongitude,
		&i.ProposedElevation,
		&i.CorrectionReason,
		&i.EvidenceUrls,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllCorrectionRequests = `-- name: GetAllCorrectionRequests :many
SELECT
  ccr.id, ccr.city_id, ccr.publisher_id, ccr.requester_email, ccr.requester_name, ccr.proposed_latitude, ccr.proposed_longitude, ccr.proposed_elevation, ccr.correction_reason, ccr.evidence_urls, ccr.status, ccr.reviewed_by, ccr.reviewed_at, ccr.review_notes, ccr.created_at, ccr.updated_at,
  c.name as city_name,
  c.latitude as current_latitude,
  c.longitude as current_longitude,
  c.elevation_m as current_elevation,
  p.name as publisher_name
FROM city_correction_requests ccr
JOIN geo_cities c ON ccr.city_id = c.id
LEFT JOIN publishers p ON ccr.publisher_id = p.id
WHERE ($1::text IS NULL OR ccr.status = $1)
ORDER BY ccr.created_at DESC
`

type GetAllCorrectionRequestsRow struct {
	ID                int32              `json:"id"`
	CityID            int64              `json:"city_id"`
	PublisherID       *int32             `json:"publisher_id"`
	RequesterEmail    string             `json:"requester_email"`
	RequesterName     *string            `json:"requester_name"`
	ProposedLatitude  *float64           `json:"proposed_latitude"`
	ProposedLongitude *float64           `json:"proposed_longitude"`
	ProposedElevation *int32             `json:"proposed_elevation"`
	CorrectionReason  string             `json:"correction_reason"`
	EvidenceUrls      []string           `json:"evidence_urls"`
	Status            string             `json:"status"`
	ReviewedBy        *string            `json:"reviewed_by"`
	ReviewedAt        pgtype.Timestamptz `json:"reviewed_at"`
	ReviewNotes       *string            `json:"review_notes"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	CityName          string             `json:"city_name"`
	CurrentLatitude   float64            `json:"current_latitude"`
	CurrentLongitude  float64            `json:"current_longitude"`
	CurrentElevation  *int32             `json:"current_elevation"`
	PublisherName     *string            `json:"publisher_name"`
}

func (q *Queries) GetAllCorrectionRequests(ctx context.Context, status *string) ([]GetAllCorrectionRequestsRow, error) {
	rows, err := q.db.Query(ctx, getAllCorrectionRequests, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllCorrectionRequestsRow{}
	for rows.Next() {
		var i GetAllCorrectionRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.CityID,
			&i.PublisherID,
			&i.RequesterEmail,
			&i.RequesterName,
			&i.ProposedLatitude,
			&i.ProposedLongitude,
			&i.ProposedElevation,
			&i.CorrectionReason,
			&i.EvidenceUrls,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.ReviewNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CityName,
			&i.CurrentLatitude,
			&i.CurrentLongitude,
			&i.CurrentElevation,
			&i.PublisherName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCorrectionRequestByID = `-- name: GetCorrectionRequestByID :one
SELECT
  ccr.id, ccr.city_id, ccr.publisher_id, ccr.requester_email, ccr.requester_name, ccr.proposed_latitude, ccr.proposed_longitude, ccr.proposed_elevation, ccr.correction_reason, ccr.evidence_urls, ccr.status, ccr.reviewed_by, ccr.reviewed_at, ccr.review_notes, ccr.created_at, ccr.updated_at,
  c.name as city_name,
  c.latitude as current_latitude,
  c.longitude as current_longitude,
  c.elevation_m as current_elevation,
  p.name as publisher_name
FROM city_correction_requests ccr
JOIN geo_cities c ON ccr.city_id = c.id
LEFT JOIN publishers p ON ccr.publisher_id = p.id
WHERE ccr.id = $1
`

type GetCorrectionRequestByIDRow struct {
	ID                int32              `json:"id"`
	CityID            int64              `json:"city_id"`
	PublisherID       *int32             `json:"publisher_id"`
	RequesterEmail    string             `json:"requester_email"`
	RequesterName     *string            `json:"requester_name"`
	ProposedLatitude  *float64           `json:"proposed_latitude"`
	ProposedLongitude *float64           `json:"proposed_longitude"`
	ProposedElevation *int32             `json:"proposed_elevation"`
	CorrectionReason  string             `json:"correction_reason"`
	EvidenceUrls      []string           `json:"evidence_urls"`
	Status            string             `json:"status"`
	ReviewedBy        *string            `json:"reviewed_by"`
	ReviewedAt        pgtype.Timestamptz `json:"reviewed_at"`
	ReviewNotes       *string            `json:"review_notes"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	CityName          string             `json:"city_name"`
	CurrentLatitude   float64            `json:"current_latitude"`
	CurrentLongitude  float64            `json:"current_longitude"`
	CurrentElevation  *int32             `json:"current_elevation"`
	PublisherName     *string            `json:"publisher_name"`
}

func (q *Queries) GetCorrectionRequestByID(ctx context.Context, id int32) (GetCorrectionRequestByIDRow, error) {
	row := q.db.QueryRow(ctx, getCorrectionRequestByID, id)
	var i GetCorrectionRequestByIDRow
	err := row.Scan(
		&i.ID,
		&i.CityID,
		&i.PublisherID,
		&i.RequesterEmail,
		&i.RequesterName,
		&i.ProposedLatitude,
		&i.ProposedLongitude,
		&i.ProposedElevation,
		&i.CorrectionReason,
		&i.EvidenceUrls,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CityName,
		&i.CurrentLatitude,
		&i.CurrentLongitude,
		&i.CurrentElevation,
		&i.PublisherName,
	)
	return i, err
}

const getPublisherCorrectionRequests = `-- name: GetPublisherCorrectionRequests :many
SELECT
  ccr.id, ccr.city_id, ccr.publisher_id, ccr.requester_email, ccr.requester_name, ccr.proposed_latitude, ccr.proposed_longitude, ccr.proposed_elevation, ccr.correction_reason, ccr.evidence_urls, ccr.status, ccr.reviewed_by, ccr.reviewed_at, ccr.review_notes, ccr.created_at, ccr.updated_at,
  c.name as city_name,
  c.latitude as current_latitude,
  c.longitude as current_longitude,
  c.elevation_m as current_elevation
FROM city_correction_requests ccr
JOIN geo_cities c ON ccr.city_id = c.id
WHERE ccr.publisher_id = $1
ORDER BY ccr.created_at DESC
`

type GetPublisherCorrectionRequestsRow struct {
	ID                int32              `json:"id"`
	CityID            int64              `json:"city_id"`
	PublisherID       *int32             `json:"publisher_id"`
	RequesterEmail    string             `json:"requester_email"`
	RequesterName     *string            `json:"requester_name"`
	ProposedLatitude  *float64           `json:"proposed_latitude"`
	ProposedLongitude *float64           `json:"proposed_longitude"`
	ProposedElevation *int32             `json:"proposed_elevation"`
	CorrectionReason  string             `json:"correction_reason"`
	EvidenceUrls      []string           `json:"evidence_urls"`
	Status            string             `json:"status"`
	ReviewedBy        *string            `json:"reviewed_by"`
	ReviewedAt        pgtype.Timestamptz `json:"reviewed_at"`
	ReviewNotes       *string            `json:"review_notes"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	CityName          string             `json:"city_name"`
	CurrentLatitude   float64            `json:"current_latitude"`
	CurrentLongitude  float64            `json:"current_longitude"`
	CurrentElevation  *int32             `json:"current_elevation"`
}

func (q *Queries) GetPublisherCorrectionRequests(ctx context.Context, publisherID *int32) ([]GetPublisherCorrectionRequestsRow, error) {
	rows, err := q.db.Query(ctx, getPublisherCorrectionRequests, publisherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPublisherCorrectionRequestsRow{}
	for rows.Next() {
		var i GetPublisherCorrectionRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.CityID,
			&i.PublisherID,
			&i.RequesterEmail,
			&i.RequesterName,
			&i.ProposedLatitude,
			&i.ProposedLongitude,
			&i.ProposedElevation,
			&i.CorrectionReason,
			&i.EvidenceUrls,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.ReviewNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CityName,
			&i.CurrentLatitude,
			&i.CurrentLongitude,
			&i.CurrentElevation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCorrectionRequestStatus = `-- name: UpdateCorrectionRequestStatus :exec
UPDATE city_correction_requests
SET
  status = $2,
  reviewed_by = $3,
  reviewed_at = now(),
  review_notes = $4,
  updated_at = now()
WHERE id = $1
`

type UpdateCorrectionRequestStatusParams struct {
	ID          int32   `json:"id"`
	Status      string  `json:"status"`
	ReviewedBy  *string `json:"reviewed_by"`
	ReviewNotes *string `json:"review_notes"`
}

func (q *Queries) UpdateCorrectionRequestStatus(ctx context.Context, arg UpdateCorrectionRequestStatusParams) error {
	_, err := q.db.Exec(ctx, updateCorrectionRequestStatus,
		arg.ID,
		arg.Status,
		arg.ReviewedBy,
		arg.ReviewNotes,
	)
	return err
}
