// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddMasterZmanFromRequest(ctx context.Context, id int32) (AddMasterZmanFromRequestRow, error)
	// Add a tag to a publisher zman (with optional is_negated)
	AddTagToPublisherZman(ctx context.Context, arg AddTagToPublisherZmanParams) error
	// Request a new tag for a zman request
	AddZmanRequestNewTag(ctx context.Context, arg AddZmanRequestNewTagParams) (AddZmanRequestNewTagRow, error)
	// Add an existing tag to a zman request
	AddZmanRequestTag(ctx context.Context, arg AddZmanRequestTagParams) (AddZmanRequestTagRow, error)
	AdminCountAlgorithms(ctx context.Context, dollar_1 string) (int64, error)
	AdminCountPublishers(ctx context.Context, dollar_1 string) (int64, error)
	AdminCreateMasterZman(ctx context.Context, arg AdminCreateMasterZmanParams) (AdminCreateMasterZmanRow, error)
	// Create master zman with audit fields
	AdminCreateMasterZmanWithAudit(ctx context.Context, arg AdminCreateMasterZmanWithAuditParams) (AdminCreateMasterZmanWithAuditRow, error)
	// Publisher Creation --
	AdminCreatePublisher(ctx context.Context, arg AdminCreatePublisherParams) (AdminCreatePublisherRow, error)
	AdminDeleteMasterZman(ctx context.Context, id int32) error
	AdminDeletePublisher(ctx context.Context, id int32) error
	// ============================================
	// ADMIN QUERIES
	// ============================================
	// Get all master zmanim for admin with optional include_hidden filter
	AdminGetAllMasterZmanim(ctx context.Context, dollar_1 interface{}) ([]AdminGetAllMasterZmanimRow, error)
	// Get all registry requests without status filter
	AdminGetAllZmanRequests(ctx context.Context) ([]AdminGetAllZmanRequestsRow, error)
	AdminGetMasterZmanByID(ctx context.Context, id int32) (AdminGetMasterZmanByIDRow, error)
	// Get master zmanim by category for admin with optional include_hidden filter
	AdminGetMasterZmanimByCategory(ctx context.Context, arg AdminGetMasterZmanimByCategoryParams) ([]AdminGetMasterZmanimByCategoryRow, error)
	AdminGetPublisher(ctx context.Context, id int32) (AdminGetPublisherRow, error)
	// Admin Statistics (legacy query for backward compatibility) --
	AdminGetPublisherStats(ctx context.Context) (AdminGetPublisherStatsRow, error)
	// Admin Statistics --
	AdminGetStatistics(ctx context.Context) (AdminGetStatisticsRow, error)
	// Get registry requests filtered by status
	AdminGetZmanRequestsByStatus(ctx context.Context, key string) ([]AdminGetZmanRequestsByStatusRow, error)
	AdminHardDeletePublisher(ctx context.Context, pPublisherID int32) ([]byte, error)
	// Admin Algorithm Management --
	AdminListAlgorithms(ctx context.Context, arg AdminListAlgorithmsParams) ([]AdminListAlgorithmsRow, error)
	// Extended Admin Publisher Listing (with all fields, including soft-deleted) --
	AdminListAllPublishers(ctx context.Context, dollar_1 bool) ([]AdminListAllPublishersRow, error)
	// Admin SQL Queries
	// SQLc will generate type-safe Go code from these queries
	// Admin Publisher Management --
	AdminListPublishers(ctx context.Context, arg AdminListPublishersParams) ([]AdminListPublishersRow, error)
	// Permanent Delete --
	AdminPermanentDeletePublisher(ctx context.Context, id int32) error
	AdminReactivatePublisher(ctx context.Context, id int32) (AdminReactivatePublisherRow, error)
	AdminRestorePublisher(ctx context.Context, id int32) (AdminRestorePublisherRow, error)
	AdminSetPublisherCertified(ctx context.Context, arg AdminSetPublisherCertifiedParams) (AdminSetPublisherCertifiedRow, error)
	// Soft Delete and Restore --
	AdminSoftDeletePublisher(ctx context.Context, arg AdminSoftDeletePublisherParams) (pgtype.Timestamptz, error)
	// Publisher Updates --
	AdminSuspendPublisher(ctx context.Context, arg AdminSuspendPublisherParams) (AdminSuspendPublisherRow, error)
	AdminToggleZmanVisibility(ctx context.Context, id int32) (AdminToggleZmanVisibilityRow, error)
	// Toggle zman visibility with audit
	AdminToggleZmanVisibilityWithAudit(ctx context.Context, id int32) (AdminToggleZmanVisibilityWithAuditRow, error)
	AdminUpdateMasterZman(ctx context.Context, arg AdminUpdateMasterZmanParams) (AdminUpdateMasterZmanRow, error)
	// Update master zman with all fields (non-dynamic version)
	AdminUpdateMasterZmanSimple(ctx context.Context, arg AdminUpdateMasterZmanSimpleParams) (AdminUpdateMasterZmanSimpleRow, error)
	AdminUpdatePublisherFields(ctx context.Context, arg AdminUpdatePublisherFieldsParams) (AdminUpdatePublisherFieldsRow, error)
	AdminUpdatePublisherStatus(ctx context.Context, arg AdminUpdatePublisherStatusParams) (AdminUpdatePublisherStatusRow, error)
	// Mark a publisher request as approved
	ApprovePublisherRequest(ctx context.Context, arg ApprovePublisherRequestParams) error
	ApproveRegistration(ctx context.Context, arg ApproveRegistrationParams) error
	// Approve a new tag request - creates the tag and updates the request
	// Step 1: Create the new tag in zman_tags table
	// This query only creates the tag, the caller must update the request separately
	ApproveTagRequest(ctx context.Context, arg ApproveTagRequestParams) (ApproveTagRequestRow, error)
	// Approve a zman request
	ApproveZmanRequest(ctx context.Context, arg ApproveZmanRequestParams) (ApproveZmanRequestRow, error)
	// Publish algorithm --
	ArchiveActiveAlgorithms(ctx context.Context, publisherID int32) error
	// Auto-add approved zman to publisher's collection
	AutoAddApprovedZman(ctx context.Context, arg AutoAddApprovedZmanParams) error
	BlockEmail(ctx context.Context, arg BlockEmailParams) error
	// Returns children of ANY entity (continent, country, region, or locality) for unified hierarchical browsing
	// When parent_type is NULL, returns all continents (top-level entities)
	// Uses pre-computed descendant_count for recursive totals
	BrowseHierarchy(ctx context.Context, arg BrowseHierarchyParams) ([]BrowseHierarchyRow, error)
	// Note: Onboarding queries moved to onboarding.sql
	// Algorithm Collaboration Queries --
	BrowsePublicAlgorithms(ctx context.Context, arg BrowsePublicAlgorithmsParams) ([]BrowsePublicAlgorithmsRow, error)
	// Browse public zmanim --
	BrowsePublicZmanim(ctx context.Context, arg BrowsePublicZmanimParams) ([]BrowsePublicZmanimRow, error)
	// Bulk insert tags for a publisher zman (with is_negated)
	BulkAddTagsToPublisherZman(ctx context.Context, arg []BulkAddTagsToPublisherZmanParams) (int64, error)
	CancelInvitation(ctx context.Context, arg CancelInvitationParams) error
	CancelRegistration(ctx context.Context, token string) error
	CheckDuplicateCorrectionRequests(ctx context.Context, localityID *int32) ([]CheckDuplicateCorrectionRequestsRow, error)
	// ============================================================================
	// Coverage Validation
	// ============================================================================
	CheckDuplicateCoverageContinent(ctx context.Context, arg CheckDuplicateCoverageContinentParams) (bool, error)
	CheckDuplicateCoverageCountry(ctx context.Context, arg CheckDuplicateCoverageCountryParams) (bool, error)
	CheckDuplicateCoverageLocality(ctx context.Context, arg CheckDuplicateCoverageLocalityParams) (bool, error)
	CheckDuplicateCoverageRegion(ctx context.Context, arg CheckDuplicateCoverageRegionParams) (bool, error)
	// Publisher Request Queries
	// These queries handle publisher registration requests (public submissions and admin review)
	// Check if there's already a pending or approved request for this email
	CheckExistingPublisherRequest(ctx context.Context, lower string) (int64, error)
	// Checks if a zman has any tag with tag_type = 'event'
	CheckIfEventZman(ctx context.Context, id int32) (bool, error)
	CheckLocalityElevationOverrideExists(ctx context.Context, arg CheckLocalityElevationOverrideExistsParams) (bool, error)
	// ============================================
	// Existence Checks
	// ============================================
	CheckLocalityLocationOverrideExists(ctx context.Context, arg CheckLocalityLocationOverrideExistsParams) (bool, error)
	CheckMasterZmanInUse(ctx context.Context, masterZmanID *int32) (bool, error)
	// Check if there's a pending/verified registration with this contact email
	CheckPendingRegistrationByContactEmail(ctx context.Context, email string) (bool, error)
	// Check if there's a pending/verified registration with this publisher name
	CheckPendingRegistrationByName(ctx context.Context, name string) (bool, error)
	// Check if a publisher with this contact email already exists (case-insensitive)
	CheckPublisherContactEmailExists(ctx context.Context, email string) (bool, error)
	// Publisher Existence and Basic Info --
	CheckPublisherExists(ctx context.Context, id int32) (bool, error)
	// Check if a publisher has already imported a specific master zman
	CheckPublisherHasMasterZman(ctx context.Context, arg CheckPublisherHasMasterZmanParams) (bool, error)
	// =============================================================================
	// DUPLICATE DETECTION
	// =============================================================================
	// Check if a publisher with this name already exists (case-insensitive)
	CheckPublisherNameExists(ctx context.Context, name string) (bool, error)
	// ============================================================================
	// Queries for Publisher Zman Linking/Copying
	// ============================================================================
	// Verify a publisher is active and verified
	CheckPublisherVerified(ctx context.Context, id int32) (bool, error)
	// System Config Management --
	// NOTE: system_config table not yet created - queries commented out
	CheckSystemConfigTableExists(ctx context.Context) (bool, error)
	// Check if a zman_key already exists for a publisher
	CheckZmanKeyExists(ctx context.Context, arg CheckZmanKeyExistsParams) (bool, error)
	// =============================================================================
	// CLEANUP
	// =============================================================================
	// Mark pending tokens as expired
	CleanupExpiredTokens(ctx context.Context) (int64, error)
	// Marks an action as completed with result data
	CompleteAction(ctx context.Context, arg CompleteActionParams) error
	ConfirmExistingUser(ctx context.Context, token string) error
	CopyPublicAlgorithm(ctx context.Context, arg CopyPublicAlgorithmParams) (int32, error)
	// Create a copied publisher zman (independent copy from another publisher)
	CopyPublisherZmanFromExample(ctx context.Context, arg CopyPublisherZmanFromExampleParams) (CopyPublisherZmanFromExampleRow, error)
	// Returns count for extended admin audit logs
	CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error)
	// Count total master zmanim matching filters (for pagination)
	CountMasterZmanimForRegistry(ctx context.Context, arg CountMasterZmanimForRegistryParams) (int64, error)
	CountPendingInvitationsForEmail(ctx context.Context, arg CountPendingInvitationsForEmailParams) (int64, error)
	CountPublicAlgorithms(ctx context.Context) (int64, error)
	// Count publisher requests by status
	CountPublisherRequestsByStatus(ctx context.Context, key string) (int64, error)
	CountPublisherZmanim(ctx context.Context, publisherID int32) (int64, error)
	// Count publisher's zmanim matching filters
	CountPublisherZmanimForExamples(ctx context.Context, arg CountPublisherZmanimForExamplesParams) (int64, error)
	CountPublishers(ctx context.Context) (int64, error)
	CountRecentInvitationsByPublisher(ctx context.Context, arg CountRecentInvitationsByPublisherParams) (int64, error)
	// Get count of tags per type (for UI display)
	CountTagsByType(ctx context.Context) ([]CountTagsByTypeRow, error)
	// Count total verified/active publishers
	CountVerifiedPublishers(ctx context.Context) (int64, error)
	// Creates an admin override for locality elevation (source='admin', publisher_id=NULL)
	// This is the highest priority system-wide elevation source
	CreateAdminElevationOverride(ctx context.Context, arg CreateAdminElevationOverrideParams) (GeoLocalityElevation, error)
	// Creates an admin override for locality coordinates (source='admin', publisher_id=NULL)
	// This is the highest priority system-wide coordinate source
	CreateAdminLocationOverride(ctx context.Context, arg CreateAdminLocationOverrideParams) (CreateAdminLocationOverrideRow, error)
	// Create or update algorithm --
	CreateAlgorithm(ctx context.Context, arg CreateAlgorithmParams) (CreateAlgorithmRow, error)
	// File: correction_requests.sql
	// Purpose: SQLc queries for locality correction requests
	// Story: 6.5 - Public Correction Requests
	CreateCorrectionRequest(ctx context.Context, arg CreateCorrectionRequestParams) (LocationCorrectionRequest, error)
	CreateCoverageContinent(ctx context.Context, arg CreateCoverageContinentParams) (CreateCoverageContinentRow, error)
	CreateCoverageCountry(ctx context.Context, arg CreateCoverageCountryParams) (CreateCoverageCountryRow, error)
	CreateCoverageLocality(ctx context.Context, arg CreateCoverageLocalityParams) (CreateCoverageLocalityRow, error)
	CreateCoverageRegion(ctx context.Context, arg CreateCoverageRegionParams) (CreateCoverageRegionRow, error)
	// Create initial version for a new publisher zman
	CreateInitialZmanVersion(ctx context.Context, arg CreateInitialZmanVersionParams) error
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (int32, error)
	// Additional invitation queries for secure user invitation flow
	// Story: 8.31 - Secure User Invitation Flow with Email Verification
	// Note: Core queries exist in admin.sql and publishers.sql
	CreateInvitationWithStatus(ctx context.Context, arg CreateInvitationWithStatusParams) (PublisherInvitation, error)
	// Create a new zman from another publisher (linked or copied)
	CreateLinkedOrCopiedZman(ctx context.Context, arg CreateLinkedOrCopiedZmanParams) (CreateLinkedOrCopiedZmanRow, error)
	// ============================================
	// Elevation Override CRUD
	// ============================================
	CreateLocalityElevationOverride(ctx context.Context, arg CreateLocalityElevationOverrideParams) (GeoLocalityElevation, error)
	// ============================================
	// Location Override Queries
	// Hierarchical location/elevation management
	// ============================================
	// ============================================
	// Resolution Function Query
	// ============================================
	// NOTE: get_effective_locality_location() is implemented in locality_locations_manual.go
	// SQLc cannot introspect PostgreSQL functions that return TABLE(...)
	// ============================================
	// Location Override CRUD
	// ============================================
	CreateLocalityLocationOverride(ctx context.Context, arg CreateLocalityLocationOverrideParams) (CreateLocalityLocationOverrideRow, error)
	CreatePublisher(ctx context.Context, arg CreatePublisherParams) (CreatePublisherRow, error)
	// Creates a publisher-specific override for locality elevation
	// This is the highest priority for this publisher's zmanim calculations
	CreatePublisherElevationOverride(ctx context.Context, arg CreatePublisherElevationOverrideParams) (GeoLocalityElevation, error)
	CreatePublisherFromImport(ctx context.Context, arg CreatePublisherFromImportParams) (CreatePublisherFromImportRow, error)
	// Create a new publisher from an approved request
	CreatePublisherFromRequest(ctx context.Context, arg CreatePublisherFromRequestParams) (CreatePublisherFromRequestRow, error)
	// ============================================
	// IMPORT AUDIT TRAIL
	// ============================================
	// Record import event in audit trail
	CreatePublisherImportHistory(ctx context.Context, arg CreatePublisherImportHistoryParams) (PublisherImportHistory, error)
	// Creates a publisher-specific override for locality coordinates
	// This is the highest priority for this publisher's zmanim calculations
	CreatePublisherLocationOverride(ctx context.Context, arg CreatePublisherLocationOverrideParams) (CreatePublisherLocationOverrideRow, error)
	// Insert a new publisher registration request
	CreatePublisherRequest(ctx context.Context, arg CreatePublisherRequestParams) (CreatePublisherRequestRow, error)
	// ============================================
	// PUBLISHER SNAPSHOT (ZMANIM-ONLY) QUERIES
	// ============================================
	// Snapshots store only zmanim data (not profile/coverage)
	// Used for version control of publisher algorithms
	CreatePublisherSnapshot(ctx context.Context, arg CreatePublisherSnapshotParams) (PublisherSnapshot, error)
	CreatePublisherZman(ctx context.Context, arg CreatePublisherZmanParams) (CreatePublisherZmanRow, error)
	// Create an alias for a publisher's zman
	CreatePublisherZmanAlias(ctx context.Context, arg CreatePublisherZmanAliasParams) (CreatePublisherZmanAliasRow, error)
	// Create publisher zman from master registry with custom formula
	CreatePublisherZmanFromMasterWithFormula(ctx context.Context, arg CreatePublisherZmanFromMasterWithFormulaParams) (CreatePublisherZmanFromMasterWithFormulaRow, error)
	CreatePublisherZmanFromRegistry(ctx context.Context, arg CreatePublisherZmanFromRegistryParams) (CreatePublisherZmanFromRegistryRow, error)
	// Create a publisher_zman entry from an approved zman request
	// This is used when auto_add_on_approval is true
	CreatePublisherZmanFromRequest(ctx context.Context, id int32) (CreatePublisherZmanFromRequestRow, error)
	// =============================================================================
	// REGISTRATION TOKEN CREATION
	// =============================================================================
	CreateRegistrationToken(ctx context.Context, arg CreateRegistrationTokenParams) (PublisherRegistrationToken, error)
	// For testing or custom expiry
	CreateRegistrationTokenWithExpiry(ctx context.Context, arg CreateRegistrationTokenWithExpiryParams) (PublisherRegistrationToken, error)
	// Create a new version entry for rollback
	CreateVersionForRollback(ctx context.Context, arg CreateVersionForRollbackParams) error
	CreateVersionSnapshot(ctx context.Context, arg CreateVersionSnapshotParams) (CreateVersionSnapshotRow, error)
	// ============================================
	// ZMAN REGISTRY REQUESTS
	// ============================================
	CreateZmanRegistryRequest(ctx context.Context, arg CreateZmanRegistryRequestParams) (CreateZmanRegistryRequestRow, error)
	// Create a new zman registry request with all fields
	CreateZmanRegistryRequestFull(ctx context.Context, arg CreateZmanRegistryRequestFullParams) (CreateZmanRegistryRequestFullRow, error)
	// Zman Request Queries
	// Epic 5, Story 5.0: Enhanced Zman Registry Requests
	// Create a new zman request from a publisher
	CreateZmanRequest(ctx context.Context, arg CreateZmanRequestParams) (CreateZmanRequestRow, error)
	CreateZmanVersion(ctx context.Context, arg CreateZmanVersionParams) (CreateZmanVersionRow, error)
	DeleteAllCountries(ctx context.Context) error
	DeleteAllPublisherCoverage(ctx context.Context, publisherID int32) error
	// Cleanup Operations --
	DeleteAllPublisherZmanim(ctx context.Context, publisherID int32) error
	DeleteAllRegions(ctx context.Context) error
	// Deletes a correction request by ID
	DeleteCorrectionRequest(ctx context.Context, id int32) error
	DeleteCoverage(ctx context.Context, id int32) error
	DeleteCoverageByPublisher(ctx context.Context, publisherID int32) error
	DeleteExpiredInvitations(ctx context.Context, publisherID int32) error
	// Hard delete very old expired/cancelled tokens (30 days)
	DeleteExpiredRegistrationTokens(ctx context.Context) error
	DeleteInvitation(ctx context.Context, id int32) error
	DeleteLocalityElevationOverride(ctx context.Context, id int32) error
	// Removes an elevation override (admin or publisher) by locality_id and optional publisher_id
	// ONLY deletes admin or publisher overrides, never base data sources
	DeleteLocalityElevationOverrideByLocality(ctx context.Context, arg DeleteLocalityElevationOverrideByLocalityParams) error
	DeleteLocalityLocationOverride(ctx context.Context, id int32) error
	// Removes a location override (admin or publisher) by locality_id and optional publisher_id
	// ONLY deletes admin or publisher overrides, never base data sources
	DeleteLocalityLocationOverrideByLocality(ctx context.Context, arg DeleteLocalityLocationOverrideByLocalityParams) error
	// ============================================
	// TAG MANAGEMENT QUERIES
	// ============================================
	DeleteMasterZmanTags(ctx context.Context, masterZmanID int32) error
	// ============================================================================
	// MAINTENANCE QUERIES
	// ============================================================================
	// Deletes calculation logs older than specified days
	// Use this to keep the raw logs table manageable
	DeleteOldCalculationLogs(ctx context.Context, dollar_1 int32) error
	DeleteOldCompletedTokens(ctx context.Context) error
	DeletePendingInvitation(ctx context.Context, id int32) (pgconn.CommandTag, error)
	DeletePublisher(ctx context.Context, id int32) error
	// Delete all coverage for a publisher (before re-importing)
	DeletePublisherCoverageForImport(ctx context.Context, publisherID int32) error
	DeletePublisherSnapshot(ctx context.Context, arg DeletePublisherSnapshotParams) error
	// Hard delete for custom zmanim only
	DeletePublisherZman(ctx context.Context, arg DeletePublisherZmanParams) (int32, error)
	// Delete an alias by ID
	DeletePublisherZmanAlias(ctx context.Context, id int32) error
	// Delete all aliases for a specific zman_key
	DeletePublisherZmanAliasByZmanKey(ctx context.Context, arg DeletePublisherZmanAliasByZmanKeyParams) error
	// Delete all tags for a publisher zman
	DeletePublisherZmanTags(ctx context.Context, publisherZmanID int32) error
	// Delete all tags for a zman request (used when updating request)
	DeleteZmanRequestTags(ctx context.Context, requestID int32) error
	DeprecateAlgorithmVersion(ctx context.Context, arg DeprecateAlgorithmVersionParams) (int64, error)
	ExpireOldInvitations(ctx context.Context) error
	// ============================================================================
	// Queries for fetchPublisherZmanim (complex join with tags and source info)
	// ============================================================================
	// Get all zmanim for a publisher with full tag and source information
	// This replaces the raw SQL query in fetchPublisherZmanim function
	// @param transliteration_style: 'ashkenazi' (default) or 'sephardi' - controls tag display names
	FetchPublisherZmanim(ctx context.Context, arg FetchPublisherZmanimParams) ([]FetchPublisherZmanimRow, error)
	// Find an existing tag by tag_key (case-insensitive match)
	FindTagByTagKey(ctx context.Context, lower string) (FindTagByTagKeyRow, error)
	ForkPublicAlgorithm(ctx context.Context, arg ForkPublicAlgorithmParams) (int32, error)
	GetAIAuditLogs(ctx context.Context, arg GetAIAuditLogsParams) ([]AiAuditLog, error)
	GetAccessiblePublishersByClerkUserID(ctx context.Context, clerkUserID *string) (GetAccessiblePublishersByClerkUserIDRow, error)
	GetAccessiblePublishersByIDs(ctx context.Context, dollar_1 []int32) ([]GetAccessiblePublishersByIDsRow, error)
	// Retrieves causal chain for an action (parent → child actions)
	GetActionChain(ctx context.Context, id string) ([]GetActionChainRow, error)
	// Retrieves all actions for a given request ID (for debugging/audit)
	GetActionsByRequest(ctx context.Context, requestID string) ([]Action, error)
	// Returns all system-wide admin elevation overrides
	GetAdminElevationOverrides(ctx context.Context) ([]GetAdminElevationOverridesRow, error)
	// ============================================
	// Admin Override Queries
	// ============================================
	// Returns all system-wide admin location overrides
	GetAdminLocationOverrides(ctx context.Context) ([]GetAdminLocationOverridesRow, error)
	GetAlgorithmByID(ctx context.Context, arg GetAlgorithmByIDParams) (GetAlgorithmByIDRow, error)
	GetAlgorithmStatusByID(ctx context.Context, id int16) (GetAlgorithmStatusByIDRow, error)
	GetAlgorithmStatusByKey(ctx context.Context, key string) (GetAlgorithmStatusByKeyRow, error)
	// Algorithm Statuses --
	GetAlgorithmStatuses(ctx context.Context) ([]GetAlgorithmStatusesRow, error)
	// Algorithm versions --
	GetAlgorithmVersions(ctx context.Context, publisherID int32) ([]GetAlgorithmVersionsRow, error)
	// ============================================
	// ASTRONOMICAL PRIMITIVES QUERIES
	// ============================================
	GetAllAstronomicalPrimitives(ctx context.Context) ([]GetAllAstronomicalPrimitivesRow, error)
	// Current coordinates/elevation resolved with priority: admin > default (for display)
	// Uses LATERAL joins to avoid materializing the full resolved_coords view for 4M+ localities
	GetAllCorrectionRequests(ctx context.Context, status *string) ([]GetAllCorrectionRequestsRow, error)
	// ============================================================================
	// DISPLAY GROUPS
	// ============================================================================
	// Get all display groups ordered by sort_order
	GetAllDisplayGroups(ctx context.Context) ([]DisplayGroup, error)
	// Master Zmanim Registry SQL Queries
	// SQLc will generate type-safe Go code from these queries
	// ============================================
	// MASTER REGISTRY QUERIES
	// ============================================
	// Orders by time_category (chronological) then hebrew_name
	GetAllMasterZmanim(ctx context.Context) ([]GetAllMasterZmanimRow, error)
	// Get metadata for all zmanim from master registry with time category key
	GetAllMasterZmanimMetadata(ctx context.Context) ([]GetAllMasterZmanimMetadataRow, error)
	// Get all aliases for a publisher with canonical names included
	// Orders by time_category (chronological) then hebrew_name
	GetAllPublisherZmanAliases(ctx context.Context, publisherID int32) ([]GetAllPublisherZmanAliasesRow, error)
	// Get all active zman keys for a publisher (for diff comparison)
	GetAllPublisherZmanimKeys(ctx context.Context, publisherID int32) ([]string, error)
	GetAllPublishersBasicInfo(ctx context.Context) ([]GetAllPublishersBasicInfoRow, error)
	// ============================================================================
	// TAG TYPES
	// ============================================================================
	// Get all tag types ordered by sort_order
	GetAllTagTypes(ctx context.Context) ([]GetAllTagTypesRow, error)
	// ============================================
	// TAG QUERIES
	// ============================================
	// User-facing query - excludes hidden tags
	GetAllTags(ctx context.Context) ([]GetAllTagsRow, error)
	// Get all zman tags for admin (includes hidden tags and is_hidden flag)
	GetAllTagsAdmin(ctx context.Context) ([]GetAllTagsAdminRow, error)
	// ============================================
	// TAG QUERIES (ADDITIONAL)
	// ============================================
	// Get all tags with custom sorting by tag type (user-facing - excludes hidden tags)
	GetAllTagsOrdered(ctx context.Context) ([]GetAllTagsOrderedRow, error)
	// REMOVED: GetTagByHebcalBasename
	// The hebcal_basename column has been removed in the new schema
	// Use match_hebcal_event() function instead for HebCal event matching
	// REMOVED: GetTagsForHebCalEvent
	// This query used the old tag_event_mappings table
	// Use the match_hebcal_event() PostgreSQL function instead
	// REMOVED: GetTagsForHebrewDate
	// This query used the old tag_event_mappings table with Hebrew date matching
	// Hebrew date matching is now handled via HebCal API integration and match_hebcal_event()
	// ============================================================================
	// All Tags Queries (with tag_key - extends master_registry.sql queries)
	// ============================================================================
	// Get all tags ordered by type and sort order (includes tag_key and multilingual names)
	// User-facing query - excludes hidden tags
	GetAllTagsWithKey(ctx context.Context) ([]GetAllTagsWithKeyRow, error)
	// Queries for time_categories and tag_types tables
	// ============================================================================
	// TIME CATEGORIES
	// ============================================================================
	// Get all time categories ordered by sort_order
	GetAllTimeCategories(ctx context.Context) ([]TimeCategory, error)
	// Get all zman requests (for admin) with optional status filter
	GetAllZmanRequests(ctx context.Context, dollar_1 string) ([]GetAllZmanRequestsRow, error)
	// Get all tags for all zmanim with tag type key, sort order, and negation status
	// Returns both Ashkenazi and Sephardi display names for Go code to select based on context
	// User-facing query - excludes hidden tags
	GetAllZmanimTags(ctx context.Context) ([]GetAllZmanimTagsRow, error)
	GetAstronomicalPrimitiveByName(ctx context.Context, variableName string) (GetAstronomicalPrimitiveByNameRow, error)
	GetAstronomicalPrimitivesByCategory(ctx context.Context, key string) ([]GetAstronomicalPrimitivesByCategoryRow, error)
	// Returns primitives with category for grouping in UI
	GetAstronomicalPrimitivesGrouped(ctx context.Context) ([]GetAstronomicalPrimitivesGroupedRow, error)
	// Returns a single audit log entry by ID
	GetAuditLogByID(ctx context.Context, id string) (GetAuditLogByIDRow, error)
	// Returns all audit logs with extended filtering for admin (includes all events, not just admin_*)
	GetAuditLogs(ctx context.Context, arg GetAuditLogsParams) ([]GetAuditLogsRow, error)
	// Returns audit statistics for the last 24 hours
	GetAuditStats24h(ctx context.Context) (int64, error)
	// Returns audit statistics for the last 7 days
	GetAuditStats7d(ctx context.Context) (int64, error)
	// Returns event counts grouped by action type
	GetAuditStatsByAction(ctx context.Context) ([]GetAuditStatsByActionRow, error)
	// Returns event counts grouped by category (concept)
	GetAuditStatsByCategory(ctx context.Context) ([]GetAuditStatsByCategoryRow, error)
	// Returns event counts grouped by status
	GetAuditStatsByStatus(ctx context.Context) ([]GetAuditStatsByStatusRow, error)
	GetBlockedEmails(ctx context.Context) ([]BlockedEmail, error)
	// Geo Boundaries SQL Queries
	// NOTE: Boundary tables (geo_country_boundaries, geo_region_boundaries) were removed
	// as part of the Overture migration. Localities are point-only.
	// This file contains placeholder queries to maintain handler compatibility.
	// ============================================================================
	// Boundary Functionality Status: DISABLED
	// ============================================================================
	// The old WOF boundary tables have been removed. The Overture schema uses
	// point-based localities without boundary polygons. If boundary functionality
	// is needed in the future, new boundary tables would need to be added.
	//
	// Removed tables:
	// - geo_country_boundaries
	// - geo_region_boundaries
	// - geo_district_boundaries
	// - geo_city_boundaries
	// - geo_locality_boundaries
	// - geo_boundary_imports
	// - geo_name_mappings
	// ============================================================================
	// Returns placeholder stats since boundaries are disabled
	GetBoundaryStats(ctx context.Context) (GetBoundaryStatsRow, error)
	GetCachedExplanation(ctx context.Context, arg GetCachedExplanationParams) (string, error)
	// Returns total count of calculation logs
	GetCalculationLogsCount(ctx context.Context) (int64, error)
	// Returns disk size of calculation_logs table
	GetCalculationLogsDiskSize(ctx context.Context) (string, error)
	// ============================================
	// COMPLETE PUBLISHER EXPORT (ADMIN/BACKUP)
	// ============================================
	// Complete export includes profile, logo, coverage, zmanim
	// Different from publisher-accessible snapshot (zmanim-only)
	// Get complete publisher data for backup/admin export
	GetCompletePublisherExport(ctx context.Context, id int32) (GetCompletePublisherExportRow, error)
	// Geo Lookups --
	GetContinentByCode(ctx context.Context, code string) (GetContinentByCodeRow, error)
	// Cities SQL Queries (Geographic Hierarchy)
	// Continent -> Country -> Region -> Locality
	// ============================================================================
	// Continents
	// ============================================================================
	// Count only localities with COMPLETE hierarchy chain (locality -> country -> continent)
	// Filter out continents with 0 localities
	GetContinents(ctx context.Context) ([]GetContinentsRow, error)
	// Current coordinates/elevation resolved with priority: admin > default (for display)
	// Original coordinates/elevation from default source (excluding admin overrides, for revert)
	// Uses LATERAL joins to avoid materializing the full resolved_coords view for 4M+ localities
	GetCorrectionRequestByID(ctx context.Context, id int32) (GetCorrectionRequestByIDRow, error)
	// Get all approved/reverted correction requests for a locality (for History & Revert tab)
	// Uses LATERAL joins to get current coordinates (before the correction was applied)
	GetCorrectionRequestHistory(ctx context.Context, localityID *int32) ([]GetCorrectionRequestHistoryRow, error)
	// ============================================================================
	// Countries
	// ============================================================================
	// Returns English name if available, otherwise native name
	// Uses subquery to get only one English name per country (prevents duplicates from multiple name entries)
	// Prefers common/official names over primary (which may contain multi-script concatenation)
	GetCountries(ctx context.Context) ([]GetCountriesRow, error)
	// Count localities via geo_search_index (uses idx_geo_search_country for O(1) lookups)
	// Filter out countries with 0 localities
	// Returns English name if available, otherwise native name
	// Prefers common/official names over primary (which may contain multi-script concatenation)
	GetCountriesByContinent(ctx context.Context, code string) ([]GetCountriesByContinentRow, error)
	// ============================================================================
	// Boundary GeoJSON Queries (for map display)
	// ============================================================================
	// Returns country boundary as GeoJSON geometry string
	// Returns empty string if no boundary exists
	GetCountryBoundaryGeoJSON(ctx context.Context, code string) (GetCountryBoundaryGeoJSONRow, error)
	// Returns English name if available, otherwise native name
	// Prefers common/official names over primary (which may contain multi-script concatenation)
	GetCountryByCode(ctx context.Context, code string) (GetCountryByCodeRow, error)
	GetCountryByCodeOrID(ctx context.Context, code string) (GetCountryByCodeOrIDRow, error)
	// Returns English name if available, otherwise native name
	// Prefers common/official names over primary (which may contain multi-script concatenation)
	GetCountryByID(ctx context.Context, id int16) (GetCountryByIDRow, error)
	GetCoverageCountByPublisher(ctx context.Context, publisherID int32) (int64, error)
	GetCoverageLevelByID(ctx context.Context, id int16) (GetCoverageLevelByIDRow, error)
	GetCoverageLevelByKey(ctx context.Context, key string) (GetCoverageLevelByKeyRow, error)
	// Lookup coverage level ID from key for import
	GetCoverageLevelIdByKey(ctx context.Context, key string) (int16, error)
	// Coverage Levels --
	GetCoverageLevels(ctx context.Context) ([]GetCoverageLevelsRow, error)
	// Version history queries --
	GetCurrentVersionNumber(ctx context.Context, algorithmID int32) (interface{}, error)
	// Get the default publisher (highest subscriber count) with their active algorithm
	GetDefaultPublisherWithAlgorithm(ctx context.Context) (GetDefaultPublisherWithAlgorithmRow, error)
	GetDeletedPublisherZmanim(ctx context.Context, publisherID int32) ([]GetDeletedPublisherZmanimRow, error)
	// Check if a zman exists in deleted state (for restore decision)
	GetDeletedZmanByKey(ctx context.Context, arg GetDeletedZmanByKeyParams) (GetDeletedZmanByKeyRow, error)
	// Get a single deleted zman's details for audit logging before restore
	GetDeletedZmanByKeyForAudit(ctx context.Context, arg GetDeletedZmanByKeyForAuditParams) (GetDeletedZmanByKeyForAuditRow, error)
	// Get direct children of a locality (sub-localities like neighborhoods)
	GetDirectChildrenOfLocality(ctx context.Context, arg GetDirectChildrenOfLocalityParams) ([]GetDirectChildrenOfLocalityRow, error)
	// Get direct children of a region (both sub-regions and localities)
	GetDirectChildrenOfRegion(ctx context.Context, arg GetDirectChildrenOfRegionParams) ([]GetDirectChildrenOfRegionRow, error)
	// Get a display group by its ID
	GetDisplayGroupByID(ctx context.Context, id int32) (DisplayGroup, error)
	// Get a display group by its key
	GetDisplayGroupByKey(ctx context.Context, key string) (DisplayGroup, error)
	// Get all distinct non-null categories for filter dropdown
	GetDistinctCategories(ctx context.Context) ([]*string, error)
	// Get all distinct non-null shitas for filter dropdown
	GetDistinctShitas(ctx context.Context) ([]*string, error)
	// Retrieves all actions for a specific entity (e.g., all actions on publisher_zman #123)
	GetEntityActionHistory(ctx context.Context, arg GetEntityActionHistoryParams) ([]GetEntityActionHistoryRow, error)
	// ============================================
	// ADDITIONAL MASTER REGISTRY QUERIES
	// ============================================
	// Get all event zmanim (those with tag_type = 'event')
	GetEventZmanim(ctx context.Context) ([]GetEventZmanimRow, error)
	// Get everyday zmanim (excludes event zmanim - those with tag_type = 'event')
	GetEverydayMasterZmanim(ctx context.Context) ([]GetEverydayMasterZmanimRow, error)
	GetExpiredInvitations(ctx context.Context, publisherID int32) ([]GetExpiredInvitationsRow, error)
	// Get only hidden tags for debugging and admin purposes
	GetHiddenTags(ctx context.Context) ([]GetHiddenTagsRow, error)
	GetInvitationByIDWithStatus(ctx context.Context, id int32) (GetInvitationByIDWithStatusRow, error)
	GetInvitationByPublisherAndEmail(ctx context.Context, arg GetInvitationByPublisherAndEmailParams) (GetInvitationByPublisherAndEmailRow, error)
	GetInvitationByToken(ctx context.Context, token string) (GetInvitationByTokenRow, error)
	GetInvitationForResend(ctx context.Context, id int32) (GetInvitationForResendRow, error)
	// Get all event tags that represent Jewish days/holidays (for calendar filtering)
	// Note: Jewish day tags are now part of 'event' type after tag consolidation
	// User-facing query - excludes hidden tags
	GetJewishDayTags(ctx context.Context) ([]GetJewishDayTagsRow, error)
	// Get algorithm ID for publisher --
	GetLatestAlgorithmByPublisher(ctx context.Context, publisherID int32) (int32, error)
	GetLatestPublisherSnapshot(ctx context.Context, publisherID int32) (PublisherSnapshot, error)
	// Returns the latest date that has been rolled up
	GetLatestRollupDate(ctx context.Context) (interface{}, error)
	// Estimates the number of localities covered by a publisher's coverage areas
	// Uses pre-computed descendant_count for accurate totals
	GetLocalitiesCoveredCount(ctx context.Context, publisherID int32) (int32, error)
	// Returns localities near a point with inherited region from search index
	// Uses GIST index on geo_locality_locations.location for fast spatial filtering
	// Priority resolution via LATERAL join AFTER spatial filter for efficiency
	GetLocalitiesNearPoint(ctx context.Context, arg GetLocalitiesNearPointParams) ([]GetLocalitiesNearPointRow, error)
	// Returns locality boundary as GeoJSON geometry string (if exists)
	// Also returns point geometry as fallback
	// Coordinates resolved with priority: admin > default (system-wide only)
	GetLocalityBoundaryGeoJSON(ctx context.Context, id int32) (GetLocalityBoundaryGeoJSONRow, error)
	// Returns locality with resolved hierarchy from search index
	// Uses geo_locality_resolved_coords view for best system-wide coordinates
	// For publisher-specific resolution, use GetEffectiveLocalityLocation from locality_locations_manual.go
	// Also returns original (non-admin) coordinates for comparison
	GetLocalityByID(ctx context.Context, id int32) (GetLocalityByIDRow, error)
	// ============================================================================
	// Queries for GetZmanimForCity handler
	// ============================================================================
	// Get locality details with country, region, and display hierarchy for zmanim calculation
	// display_hierarchy contains the full location chain (e.g., "Prestwich, Bury, England, United Kingdom")
	// Elevation defaults to 0 if NULL (sea level) - required for accurate zmanim
	// Region is resolved from geo_search_index.inherited_region_id (pre-computed during import)
	// Coordinates/elevation resolved with priority: admin > default (system-wide only, no publisher context)
	GetLocalityDetailsForZmanim(ctx context.Context, id int32) (GetLocalityDetailsForZmanimRow, error)
	GetLocalityElevationOverrideByID(ctx context.Context, id int32) (GeoLocalityElevation, error)
	// Returns all elevation overrides for a locality
	GetLocalityElevationOverrides(ctx context.Context, localityID int32) ([]GetLocalityElevationOverridesRow, error)
	// Fetches locality details with timezone for report location section
	// NOTE: Coordinates/elevation are resolved separately via GetEffectiveLocalityLocation for publisher-aware overrides
	GetLocalityForReport(ctx context.Context, id int32) (GetLocalityForReportRow, error)
	GetLocalityLocationOverrideByID(ctx context.Context, id int32) (GetLocalityLocationOverrideByIDRow, error)
	// ============================================
	// List Overrides by Locality (Admin View)
	// ============================================
	// Returns all location overrides for a locality (shows all sources)
	GetLocalityLocationOverrides(ctx context.Context, localityID int32) ([]GetLocalityLocationOverridesRow, error)
	GetLocalityTypes(ctx context.Context) ([]GeoLocalityType, error)
	// Returns locality with full hierarchy from search index
	// Uses geo_locality_resolved_coords view for best system-wide coordinates
	GetLocalityWithHierarchy(ctx context.Context, id int32) (GetLocalityWithHierarchyRow, error)
	GetMasterZmanByID(ctx context.Context, id int32) (GetMasterZmanByIDRow, error)
	GetMasterZmanByKey(ctx context.Context, zmanKey string) (GetMasterZmanByKeyRow, error)
	// Get default formula from master registry
	GetMasterZmanDefaultFormula(ctx context.Context, id int32) (*string, error)
	// Get full documentation for a master zman (for documentation modal)
	GetMasterZmanDocumentation(ctx context.Context, id int32) (GetMasterZmanDocumentationRow, error)
	// Get master zman details for import (used by import handler)
	GetMasterZmanForImport(ctx context.Context, id int32) (GetMasterZmanForImportRow, error)
	// Get tags for master zman detail view (user-facing - excludes hidden tags)
	GetMasterZmanTagsForDetail(ctx context.Context, masterZmanID int32) ([]GetMasterZmanTagsForDetailRow, error)
	// Get tags for multiple zmanim with full tag details (user-facing - excludes hidden tags)
	GetMasterZmanTagsWithDetails(ctx context.Context, dollar_1 []int32) ([]GetMasterZmanTagsWithDetailsRow, error)
	GetMasterZmanimByCategory(ctx context.Context, key string) ([]GetMasterZmanimByCategoryRow, error)
	GetMasterZmanimByTag(ctx context.Context, tagKey string) ([]GetMasterZmanimByTagRow, error)
	// Get master registry zmanim that have any of the specified tags
	GetMasterZmanimByTags(ctx context.Context, dollar_1 []string) ([]GetMasterZmanimByTagsRow, error)
	// Get master zmanim formulas by their keys for resolving @references in formulas
	GetMasterZmanimFormulasByKeys(ctx context.Context, dollar_1 []string) ([]GetMasterZmanimFormulasByKeysRow, error)
	GetMasterZmanimGroupedByCategory(ctx context.Context) ([]GetMasterZmanimGroupedByCategoryRow, error)
	// Get metadata for specific zmanim from master registry (performance optimized)
	GetMasterZmanimMetadataForKeys(ctx context.Context, dollar_1 []string) ([]GetMasterZmanimMetadataForKeysRow, error)
	// ============================================================================
	// Geolocation
	// ============================================================================
	// Find the nearest locality to given coordinates using PostGIS
	// Returns English names if available, otherwise native names
	// Uses geo_search_index.inherited_region_id for region resolution
	// Coordinates resolved with priority: admin > default (system-wide only, no publisher context)
	GetNearestLocality(ctx context.Context, arg GetNearestLocalityParams) (GetNearestLocalityRow, error)
	GetNextVersionNumber(ctx context.Context, pAlgorithmID int32) (int32, error)
	// Publisher Invitations --
	// Schema: id, publisher_id, email, role_id, token, expires_at, created_at
	GetPendingInvitations(ctx context.Context, publisherID int32) ([]GetPendingInvitationsRow, error)
	// Get count of pending zman requests (for admin dashboard)
	GetPendingZmanRequestCount(ctx context.Context) (int64, error)
	// Returns calculations for current month across all publishers
	GetPlatformMonthlyCalculations(ctx context.Context) (int64, error)
	// Returns comprehensive platform-wide stats
	GetPlatformStatsDetailed(ctx context.Context) (GetPlatformStatsDetailedRow, error)
	// Returns calculation stats grouped by publisher for admin dashboard
	GetPlatformStatsPerPublisher(ctx context.Context, limit int32) ([]GetPlatformStatsPerPublisherRow, error)
	// ============================================================================
	// PLATFORM-WIDE STATS (Admin Dashboard)
	// ============================================================================
	// Returns total calculations across all publishers
	GetPlatformTotalCalculations(ctx context.Context) (int64, error)
	GetPublicAlgorithmByID(ctx context.Context, id int32) (GetPublicAlgorithmByIDRow, error)
	GetPublicAlgorithmConfig(ctx context.Context, id int32) (GetPublicAlgorithmConfigRow, error)
	GetPublicAlgorithmWithPublisher(ctx context.Context, id int32) (GetPublicAlgorithmWithPublisherRow, error)
	GetPublisherActiveAlgorithm(ctx context.Context, publisherID int32) (GetPublisherActiveAlgorithmRow, error)
	// Retrieves all activities for a publisher (for activity log display)
	GetPublisherActivities(ctx context.Context, arg GetPublisherActivitiesParams) ([]GetPublisherActivitiesRow, error)
	// Get publisher's published algorithm configuration
	GetPublisherAlgorithm(ctx context.Context, publisherID int32) ([]byte, error)
	GetPublisherAlgorithmSummary(ctx context.Context, publisherID int32) (GetPublisherAlgorithmSummaryRow, error)
	// Returns average response time for a publisher
	GetPublisherAvgResponseTime(ctx context.Context, publisherID int32) (int32, error)
	GetPublisherBasic(ctx context.Context, id int32) (GetPublisherBasicRow, error)
	GetPublisherBasicByClerkUserID(ctx context.Context, clerkUserID *string) (GetPublisherBasicByClerkUserIDRow, error)
	// Get beta status for zmanim for a publisher
	GetPublisherBetaZmanim(ctx context.Context, publisherID int32) ([]GetPublisherBetaZmanimRow, error)
	GetPublisherByClerkUserID(ctx context.Context, clerkUserID *string) (int32, error)
	// Publishers SQL Queries
	// SQLc will generate type-safe Go code from these queries
	GetPublisherByID(ctx context.Context, id int32) (GetPublisherByIDRow, error)
	// Get publisher by ID (legacy format)
	GetPublisherByIDLegacy(ctx context.Context, id int32) (GetPublisherByIDLegacyRow, error)
	// Get a single publisher by ID for display
	GetPublisherByIdForExamples(ctx context.Context, id int32) (GetPublisherByIdForExamplesRow, error)
	// Returns cache hit ratio for a publisher
	GetPublisherCacheHitRatio(ctx context.Context, publisherID int32) (GetPublisherCacheHitRatioRow, error)
	GetPublisherCalculationSettings(ctx context.Context, id int32) (GetPublisherCalculationSettingsRow, error)
	// Current coordinates/elevation resolved with priority: admin > default (for display)
	// Uses LATERAL joins to avoid materializing the full resolved_coords view for 4M+ localities
	GetPublisherCorrectionRequests(ctx context.Context, publisherID *int32) ([]GetPublisherCorrectionRequestsRow, error)
	// Coverage SQL Queries (Geographic Hierarchy)
	// Supports: continent, country, region, locality
	// Uses geo_search_index for resolved hierarchy lookups
	// Returns coverage with full hierarchy resolved
	// Locality coordinates resolved with priority: admin > default (for display preview)
	// Direct joins for each level
	// Hierarchy traversal: country -> continent
	// Hierarchy traversal: region -> country
	// Hierarchy traversal: locality -> country (via search index)
	GetPublisherCoverage(ctx context.Context, publisherID int32) ([]GetPublisherCoverageRow, error)
	GetPublisherCoverageByID(ctx context.Context, id int32) (GetPublisherCoverageByIDRow, error)
	GetPublisherCoverageCount(ctx context.Context, publisherID int32) (int64, error)
	// Get all coverage areas for complete export
	GetPublisherCoverageForExport(ctx context.Context, publisherID int32) ([]GetPublisherCoverageForExportRow, error)
	// Get localities where a publisher has coverage
	GetPublisherCoverageLocalities(ctx context.Context, publisherID int32) ([]GetPublisherCoverageLocalitiesRow, error)
	GetPublisherDashboardSummary(ctx context.Context, id int32) (GetPublisherDashboardSummaryRow, error)
	// Algorithms SQL Queries
	// SQLc will generate type-safe Go code from these queries
	// Get algorithm for publisher --
	GetPublisherDraftAlgorithm(ctx context.Context, publisherID int32) (GetPublisherDraftAlgorithmRow, error)
	// Get a publisher's specific elevation override for a locality
	GetPublisherElevationOverrideByLocality(ctx context.Context, arg GetPublisherElevationOverrideByLocalityParams) (GetPublisherElevationOverrideByLocalityRow, error)
	// Returns all elevation overrides for a specific publisher
	GetPublisherElevationOverrides(ctx context.Context, publisherID *int32) ([]GetPublisherElevationOverridesRow, error)
	GetPublisherEmailAndName(ctx context.Context, id int32) (GetPublisherEmailAndNameRow, error)
	// Find the best publisher for a location with their active algorithm
	// Uses publisher_coverage to find publishers covering the location
	GetPublisherForLocationWithAlgorithm(ctx context.Context, localityID *int32) (GetPublisherForLocationWithAlgorithmRow, error)
	// Publisher Reports Queries
	// Used for generating PDF reports of zmanim calculations
	// Fetches publisher details needed for PDF report header
	GetPublisherForReport(ctx context.Context, id int32) (GetPublisherForReportRow, error)
	GetPublisherForks(ctx context.Context, publisherID int32) ([]GetPublisherForksRow, error)
	GetPublisherFullByClerkUserID(ctx context.Context, clerkUserID *string) (GetPublisherFullByClerkUserIDRow, error)
	GetPublisherFullProfileByClerkUserID(ctx context.Context, clerkUserID *string) (GetPublisherFullProfileByClerkUserIDRow, error)
	GetPublisherFullProfileByID(ctx context.Context, id int32) (GetPublisherFullProfileByIDRow, error)
	// Version History SQL Queries
	// SQLc will generate type-safe Go code from these queries
	// Get publisher ID by clerk user ID --
	GetPublisherIDByClerkUserID(ctx context.Context, clerkUserID *string) (int32, error)
	// Get publisher info (logo_data is the base64 embedded logo)
	GetPublisherInfoForZmanim(ctx context.Context, id int32) (GetPublisherInfoForZmanimRow, error)
	// Get publisher's is_global status
	GetPublisherIsGlobal(ctx context.Context, id int32) (bool, error)
	// Uses geo_search_index.inherited_region_id for accurate region locality counts
	GetPublisherLocalitiesCovered(ctx context.Context, publisherID int32) (int64, error)
	// Get a publisher's specific override for a locality
	GetPublisherLocationOverrideByLocality(ctx context.Context, arg GetPublisherLocationOverrideByLocalityParams) (GetPublisherLocationOverrideByLocalityRow, error)
	// ============================================
	// Publisher-specific Override Queries
	// ============================================
	// Returns all location overrides for a specific publisher
	GetPublisherLocationOverridesNew(ctx context.Context, publisherID *int32) ([]GetPublisherLocationOverridesNewRow, error)
	// Returns calculations for current month from pre-aggregated stats
	GetPublisherMonthlyCalculations(ctx context.Context, publisherID int32) (int64, error)
	// Returns stats for current month
	GetPublisherMonthlyStatsDetailed(ctx context.Context, publisherID int32) (GetPublisherMonthlyStatsDetailedRow, error)
	GetPublisherNameAndDeletedAt(ctx context.Context, id int32) (GetPublisherNameAndDeletedAtRow, error)
	GetPublisherNameByID(ctx context.Context, id int32) (string, error)
	GetPublisherNameForTeam(ctx context.Context, id int32) (string, error)
	GetPublisherNamesByIDs(ctx context.Context, dollar_1 []string) ([]GetPublisherNamesByIDsRow, error)
	// Team Management --
	GetPublisherOwner(ctx context.Context, id int32) (*string, error)
	// Team/Invitation Queries
	GetPublisherOwnerID(ctx context.Context, id int32) (*string, error)
	GetPublisherProfileByClerkUserID(ctx context.Context, clerkUserID *string) (GetPublisherProfileByClerkUserIDRow, error)
	GetPublisherProfileByID(ctx context.Context, id int32) (GetPublisherProfileByIDRow, error)
	// Get a specific publisher request by ID
	GetPublisherRequestByID(ctx context.Context, id int32) (GetPublisherRequestByIDRow, error)
	// Get publisher requests filtered by status
	GetPublisherRequestsByStatus(ctx context.Context, key string) ([]GetPublisherRequestsByStatusRow, error)
	GetPublisherRoleByID(ctx context.Context, id int16) (GetPublisherRoleByIDRow, error)
	GetPublisherRoleByKey(ctx context.Context, key string) (GetPublisherRoleByKeyRow, error)
	// Publisher Roles --
	GetPublisherRoles(ctx context.Context) ([]GetPublisherRolesRow, error)
	GetPublisherSnapshot(ctx context.Context, arg GetPublisherSnapshotParams) (PublisherSnapshot, error)
	// Returns comprehensive stats for a publisher from pre-aggregated table
	GetPublisherStatsDetailed(ctx context.Context, publisherID int32) (GetPublisherStatsDetailedRow, error)
	GetPublisherStatusByID(ctx context.Context, id int16) (GetPublisherStatusByIDRow, error)
	GetPublisherStatusByKey(ctx context.Context, key string) (GetPublisherStatusByKeyRow, error)
	// Lookup Tables SQL Queries
	// Provides access to all lookup/reference tables for frontend dropdowns and validation
	// Publisher Statuses --
	GetPublisherStatuses(ctx context.Context) ([]GetPublisherStatusesRow, error)
	// Calculation Logging Queries
	// Story 8.2: Implement Calculation Logging
	//
	// Note: Batch inserts are handled via pgx COPY protocol in the service layer
	// These queries are for stats aggregation and analytics
	// ============================================================================
	// STATS AGGREGATION QUERIES (Using Pre-Aggregated Table)
	// ============================================================================
	// Returns total calculations for a publisher from pre-aggregated stats
	GetPublisherTotalCalculations(ctx context.Context, publisherID int32) (int64, error)
	// Get publisher's preferred English transliteration style (ashkenazi or sephardi)
	GetPublisherTransliterationStyle(ctx context.Context, id int32) (string, error)
	// Alias CRUD Queries
	// Epic 5, Story 5.0: Publisher Zman Aliases
	// Schema: id, publisher_zman_id, publisher_id, alias_hebrew, alias_english, alias_transliteration, context, is_primary, created_at
	// Get a specific alias for a publisher's zman by zman_key
	GetPublisherZmanAlias(ctx context.Context, arg GetPublisherZmanAliasParams) (GetPublisherZmanAliasRow, error)
	// Get a specific zman by ID (for linking validation)
	GetPublisherZmanByID(ctx context.Context, id int32) (GetPublisherZmanByIDRow, error)
	GetPublisherZmanByKey(ctx context.Context, arg GetPublisherZmanByKeyParams) (GetPublisherZmanByKeyRow, error)
	// Simplified version of GetPublisherZmanByKey without tag aggregation
	GetPublisherZmanByKeySimplified(ctx context.Context, arg GetPublisherZmanByKeySimplifiedParams) (GetPublisherZmanByKeySimplifiedRow, error)
	// ============================================
	// PUBLISHER ZMAN DOCUMENTATION (Story 11.4)
	// ============================================
	// Get publisher zman details including source attribution and master reference
	GetPublisherZmanDocumentation(ctx context.Context, id int32) (GetPublisherZmanDocumentationRow, error)
	// Get a publisher zman by ID for linking/copying
	GetPublisherZmanForLinkCopy(ctx context.Context, id int32) (GetPublisherZmanForLinkCopyRow, error)
	// Get a specific zman by key for comparison during restore
	GetPublisherZmanForSnapshotCompare(ctx context.Context, arg GetPublisherZmanForSnapshotCompareParams) (GetPublisherZmanForSnapshotCompareRow, error)
	// ============================================================================
	// Helper Queries for Publisher Zman Operations
	// ============================================================================
	// Get publisher zman ID by publisher ID and zman key
	GetPublisherZmanIDByKey(ctx context.Context, arg GetPublisherZmanIDByKeyParams) (int32, error)
	// Get all zman requests for a specific publisher
	GetPublisherZmanRequests(ctx context.Context, publisherID int32) ([]GetPublisherZmanRequestsRow, error)
	// ============================================================================
	// Publisher Zman Tags
	// ============================================================================
	// Get all tags for a specific publisher zman (including is_negated)
	// User-facing query - excludes hidden tags
	GetPublisherZmanTags(ctx context.Context, publisherZmanID int32) ([]GetPublisherZmanTagsRow, error)
	// ============================================
	// TAG EXPORT QUERIES
	// ============================================
	// Get all tags for a specific zman for export
	GetPublisherZmanTagsForExport(ctx context.Context, publisherZmanID int32) ([]GetPublisherZmanTagsForExportRow, error)
	GetPublisherZmanWithRegistry(ctx context.Context, arg GetPublisherZmanWithRegistryParams) (GetPublisherZmanWithRegistryRow, error)
	// Zmanim SQL Queries
	// SQLc will generate type-safe Go code from these queries
	// Publisher Zmanim --
	// Orders by time_category (chronological) then hebrew_name
	GetPublisherZmanim(ctx context.Context, publisherID int32) ([]GetPublisherZmanimRow, error)
	// Get all zmanim for complete export
	GetPublisherZmanimForCompleteExport(ctx context.Context, publisherID int32) ([]GetPublisherZmanimForCompleteExportRow, error)
	// File: external_api.sql
	// Purpose: External API queries for M2M authentication endpoints
	// Epic: 8 - Finalize and External API
	// Story: 8.5 - List Publisher Zmanim for External API
	// Returns all enabled zmanim for a publisher for external API consumers
	// Includes formula metadata (type and summary) for transparency
	GetPublisherZmanimForExternal(ctx context.Context, publisherID int32) ([]GetPublisherZmanimForExternalRow, error)
	// Get published zmanim from a specific publisher for copying/linking
	// Orders by category chronologically then hebrew_name
	GetPublisherZmanimForLinking(ctx context.Context, arg GetPublisherZmanimForLinkingParams) ([]GetPublisherZmanimForLinkingRow, error)
	// ============================================
	// ZMANIM SNAPSHOT DATA QUERIES
	// ============================================
	// Get all active (non-deleted) zmanim for snapshot export
	GetPublisherZmanimForSnapshot(ctx context.Context, publisherID int32) ([]GetPublisherZmanimForSnapshotRow, error)
	// Get per-zman settings (rounding_mode, is_beta) for all zmanim for a publisher
	// Used by public zmanim API to apply publisher settings when displaying times
	GetPublisherZmanimSettings(ctx context.Context, publisherID int32) ([]GetPublisherZmanimSettingsRow, error)
	// File: zmanim_simplified.sql
	// Purpose: Simplified publisher zmanim queries (tags fetched separately)
	// Pattern: query-decomposition
	// Complexity: medium (5 concepts: publisher_zmanim, publishers, master_registry, lookup tables)
	// Used by: publisher_zmanim.go handlers
	// Note: This is a cleaner alternative to the complex GetPublisherZmanim query
	// Simplified version without tag aggregation (tags fetched separately via GetZmanTags)
	// Still includes linked source resolution and master registry fallbacks
	GetPublisherZmanimSimplified(ctx context.Context, arg GetPublisherZmanimSimplifiedParams) ([]GetPublisherZmanimSimplifiedRow, error)
	// ============================================
	// PUBLISHER ZMANIM WITH REGISTRY (new model)
	// ============================================
	GetPublisherZmanimWithRegistry(ctx context.Context, publisherID int32) ([]GetPublisherZmanimWithRegistryRow, error)
	// Find publishers with coverage in a specific country
	GetPublishersByCountry(ctx context.Context, countryID *int16) ([]GetPublishersByCountryRow, error)
	// Find publishers with coverage in a specific region
	// Uses inherited_region_id from search index
	GetPublishersByRegion(ctx context.Context, regionID *int32) ([]GetPublishersByRegionRow, error)
	// ============================================================================
	// Publisher Lookup by Location
	// ============================================================================
	// Find publishers that cover a specific locality through all coverage levels
	// Uses search index to resolve inherited_region_id
	// DISTINCT ON ensures each publisher appears only once, with most specific coverage
	GetPublishersForLocality(ctx context.Context, localityID int32) ([]GetPublishersForLocalityRow, error)
	// Get all publisher IDs that have a zman referencing this master registry entry
	// Used for cache invalidation when master zman formula changes
	GetPublishersUsingMasterZman(ctx context.Context, masterZmanID *int32) ([]int32, error)
	// Returns recent events with error or failed status (simulating critical severity)
	GetRecentCriticalEvents(ctx context.Context, limit int32) ([]GetRecentCriticalEventsRow, error)
	// Returns region boundary as GeoJSON geometry string
	// Returns empty string if no boundary exists
	GetRegionBoundaryGeoJSON(ctx context.Context, id int32) (GetRegionBoundaryGeoJSONRow, error)
	GetRegionByID(ctx context.Context, id int32) (GetRegionByIDRow, error)
	GetRegionTypes(ctx context.Context) ([]GeoRegionType, error)
	// ============================================================================
	// Regions (ADM1)
	// ============================================================================
	// Returns all regions for a country with their locality counts
	// Uses geo_search_index.inherited_region_id for accurate locality counts
	GetRegionsByCountry(ctx context.Context, code string) ([]GetRegionsByCountryRow, error)
	// Get all registrations for an email (for duplicate detection)
	GetRegistrationByEmail(ctx context.Context, email string) ([]PublisherRegistrationToken, error)
	GetRegistrationTokenByID(ctx context.Context, id string) (PublisherRegistrationToken, error)
	// =============================================================================
	// TOKEN LOOKUP
	// =============================================================================
	GetRegistrationTokenByToken(ctx context.Context, token string) (PublisherRegistrationToken, error)
	// =============================================================================
	// STATISTICS
	// =============================================================================
	GetRegistrationTokenStats(ctx context.Context) (GetRegistrationTokenStatsRow, error)
	GetRegistrationsByStatus(ctx context.Context, status string) ([]PublisherRegistrationToken, error)
	// Get basic info for related zmanim (by array of IDs)
	GetRelatedZmanimDetails(ctx context.Context, dollar_1 []int64) ([]GetRelatedZmanimDetailsRow, error)
	// Returns one representative locality per coverage area using ID-based joins
	// Used by Algorithm Editor to get preview locations for zmanim calculation
	// Uses separate LATERAL joins per coverage level for optimal index usage (~6ms vs 5s)
	// Locality lookup (direct entity match)
	// Region lookup (top locality by population in region)
	// Country lookup (top locality by population in country)
	// Continent lookup (top locality by population in continent)
	GetRepresentativeLocalitiesForCoverage(ctx context.Context, publisherID int32) ([]GetRepresentativeLocalitiesForCoverageRow, error)
	GetRequestHistory(ctx context.Context, correctionRequestID int32) ([]CorrectionRequestHistory, error)
	GetRequestStatusByKey(ctx context.Context, key string) (GetRequestStatusByKeyRow, error)
	// Request Statuses --
	GetRequestStatuses(ctx context.Context) ([]GetRequestStatusesRow, error)
	GetSearchIndexStats(ctx context.Context) (GetSearchIndexStatsRow, error)
	// Get source zman for copying/linking with publisher verification
	GetSourceZmanForLinking(ctx context.Context, id int32) (GetSourceZmanForLinkingRow, error)
	// Get a single tag by its key
	GetTagByKey(ctx context.Context, tagKey string) (GetTagByKeyRow, error)
	GetTagByTagKey(ctx context.Context, tagKey string) (GetTagByTagKeyRow, error)
	// Tag Events SQL Queries
	// SQLc will generate type-safe Go code from these queries
	// ============================================================================
	// Tag Event Mappings
	// ============================================================================
	// Get all HebCal event mappings for tag matching
	// Uses new schema where match data is stored directly in zman_tags
	GetTagEventMappings(ctx context.Context) ([]GetTagEventMappingsRow, error)
	// Removed: Duplicate of GetTagTypeByKey in lookups.sql
	// Get a tag type by its ID
	GetTagTypeByID(ctx context.Context, id int32) (GetTagTypeByIDRow, error)
	GetTagTypeByKey(ctx context.Context, key string) (GetTagTypeByKeyRow, error)
	// Tag Types --
	GetTagTypes(ctx context.Context) ([]GetTagTypesRow, error)
	// Get multiple tags by their keys
	GetTagsByKeys(ctx context.Context, dollar_1 []string) ([]GetTagsByKeysRow, error)
	// User-facing query - excludes hidden tags
	GetTagsByType(ctx context.Context, key string) ([]GetTagsByTypeRow, error)
	// User-facing query - excludes hidden tags
	GetTagsForMasterZman(ctx context.Context, masterZmanID int32) ([]GetTagsForMasterZmanRow, error)
	// Get a time category by its ID
	GetTimeCategoryByID(ctx context.Context, id int32) (TimeCategory, error)
	// Get a time category by its key
	GetTimeCategoryByKey(ctx context.Context, key string) (TimeCategory, error)
	// Lookup time category ID from key for import
	GetTimeCategoryIDByKey(ctx context.Context, key string) (int32, error)
	// Returns top actors by event count
	GetTopActors(ctx context.Context, limit int32) ([]GetTopActorsRow, error)
	// ============================================================================
	// Location Picker
	// ============================================================================
	// Get top localities ordered by population for location picker
	// Coordinates resolved with priority: admin > default (system-wide only)
	GetTopLocalitiesAsLocations(ctx context.Context, limit int32) ([]GetTopLocalitiesAsLocationsRow, error)
	// Returns top publishers by event count
	GetTopPublishers(ctx context.Context, limit int32) ([]GetTopPublishersRow, error)
	// File: zmanim_unified.sql
	// Purpose: Unified publisher zmanim queries - consolidates GetPublisherZmanim and FetchPublisherZmanim
	// Pattern: query-consolidation
	// Compliance: DRY - single query with optional parameters (sqlc.narg)
	// Replaces: GetPublisherZmanim, FetchPublisherZmanim (80% duplicate logic)
	// Used by: UnifiedZmanimService (future), publisher_zmanim.go handlers
	// Universal query for publisher zmanim - all filters are optional
	// Uses sqlc.narg() for nullable parameters to handle multiple use cases:
	// 1. Publisher dashboard (active only)
	// 2. Admin views (include deleted)
	// 3. Algorithm page (include disabled, unpublished)
	// 4. Diff/revert UI (include source info)
	GetUnifiedPublisherZmanim(ctx context.Context, arg GetUnifiedPublisherZmanimParams) ([]GetUnifiedPublisherZmanimRow, error)
	// ============================================================================
	// Queries for GetVerifiedPublishers
	// ============================================================================
	// Get verified publishers with zmanim count, excluding specified publisher
	GetVerifiedPublishers(ctx context.Context, id int32) ([]GetVerifiedPublishersRow, error)
	// Linked Zmanim Support --
	// Get verified publishers that current publisher can link to (excludes self)
	GetVerifiedPublishersForLinking(ctx context.Context, id int32) ([]GetVerifiedPublishersForLinkingRow, error)
	// =============================================================================
	// ADMIN REVIEW
	// =============================================================================
	// Get all verified applications ready for admin review
	GetVerifiedRegistrations(ctx context.Context) ([]PublisherRegistrationToken, error)
	GetVersionConfig(ctx context.Context, arg GetVersionConfigParams) ([]byte, error)
	GetVersionDetail(ctx context.Context, arg GetVersionDetailParams) (GetVersionDetailRow, error)
	// ============================================
	// ADDITIONAL QUERIES FOR MASTER_REGISTRY HANDLER
	// ============================================
	// Get formula from a specific version for rollback
	GetVersionFormula(ctx context.Context, arg GetVersionFormulaParams) (*string, error)
	// ============================================
	// AI CONTEXT QUERIES
	// ============================================
	// Get enriched zman context for AI formula generation/explanation
	// Returns master registry data, publisher-specific data (if publisher_id provided), and tags as JSON
	GetZmanContextForAI(ctx context.Context, arg GetZmanContextForAIParams) (GetZmanContextForAIRow, error)
	GetZmanRegistryRequestByID(ctx context.Context, id int32) (GetZmanRegistryRequestByIDRow, error)
	GetZmanRegistryRequests(ctx context.Context, status *string) ([]GetZmanRegistryRequestsRow, error)
	// Get a specific zman request by ID
	GetZmanRequest(ctx context.Context, id int32) (GetZmanRequestRow, error)
	// Get a specific tag request by ID
	GetZmanRequestTag(ctx context.Context, id int32) (ZmanRequestTag, error)
	// Get all tags (existing and requested) for a zman request
	GetZmanRequestTags(ctx context.Context, requestID int32) ([]GetZmanRequestTagsRow, error)
	// ============================================
	// IMPORT QUERIES
	// ============================================
	// Lookup tag ID from tag key for import
	GetZmanTagIdByKey(ctx context.Context, tagKey string) (int32, error)
	// File: zmanim_tags.sql
	// Purpose: Separate tag fetching queries (extracted from complex GetPublisherZmanim)
	// Pattern: query-decomposition
	// Complexity: low (single concept with lookup tables)
	// Used by: publisher_zmanim.go handlers
	// Fetches all tags for a specific publisher zman with source tracking
	// Combines master zman tags (if linked to master registry) with publisher-specific tags
	// Includes source_is_negated, is_modified, and tag_source for modification tracking
	// User-facing query - excludes hidden tags
	GetZmanTags(ctx context.Context, id int32) ([]GetZmanTagsRow, error)
	// Fetch tags for multiple zmanim at once (avoids N+1 queries)
	// Used when tags are needed separately from main query (e.g., simplified queries)
	// Returns tags with is_modified flag to show which tags differ from master registry
	GetZmanTagsBatch(ctx context.Context, dollar_1 []int32) ([]GetZmanTagsBatchRow, error)
	GetZmanVersion(ctx context.Context, arg GetZmanVersionParams) (GetZmanVersionRow, error)
	// ============================================
	// VERSION HISTORY QUERIES
	// ============================================
	GetZmanVersionHistory(ctx context.Context, arg GetZmanVersionHistoryParams) ([]GetZmanVersionHistoryRow, error)
	// ============================================================================
	// Tag Types Metadata
	// ============================================================================
	// Removed: Duplicate of GetTagTypes in lookups.sql
	// ============================================================================
	// Publisher Zmanim by Active Tags
	// ============================================================================
	// Get publisher zmanim that have any of the specified tags (for calendar day filtering)
	GetZmanimByActiveTags(ctx context.Context, arg GetZmanimByActiveTagsParams) ([]GetZmanimByActiveTagsRow, error)
	// Get tags for specific zmanim only (performance optimized)
	GetZmanimTagsForKeys(ctx context.Context, dollar_1 []string) ([]GetZmanimTagsForKeysRow, error)
	// Get all of a publisher's zmanim with their primary alias (if any)
	// Orders by time_category (chronological) then hebrew_name
	GetZmanimWithAliases(ctx context.Context, publisherID int32) ([]GetZmanimWithAliasesRow, error)
	// Import all everyday zmanim (excludes event zmanim - those with tag_type = 'event') for a publisher
	// Used when importing "defaults" for a new publisher
	ImportEverydayZmanimFromRegistry(ctx context.Context, publisherID int32) ([]ImportEverydayZmanimFromRegistryRow, error)
	ImportZmanimFromRegistryByKeys(ctx context.Context, arg ImportZmanimFromRegistryByKeysParams) ([]ImportZmanimFromRegistryByKeysRow, error)
	IncrementAlgorithmForkCount(ctx context.Context, id int32) error
	InsertAIAuditLog(ctx context.Context, arg InsertAIAuditLogParams) error
	InsertCorrectionHistory(ctx context.Context, arg InsertCorrectionHistoryParams) (CorrectionRequestHistory, error)
	// ============================================================================
	// Insert/Update Operations
	// ============================================================================
	InsertCountry(ctx context.Context, arg InsertCountryParams) (int16, error)
	InsertMasterZmanTag(ctx context.Context, arg InsertMasterZmanTagParams) error
	// Insert coverage area from import (assumes coverage was deleted first)
	InsertPublisherCoverageFromImport(ctx context.Context, arg InsertPublisherCoverageFromImportParams) (int32, error)
	// Insert a new publisher zman from import data
	InsertPublisherZmanFromImport(ctx context.Context, arg InsertPublisherZmanFromImportParams) error
	// Insert a tag for a publisher zman with is_negated
	InsertPublisherZmanTag(ctx context.Context, arg InsertPublisherZmanTagParams) error
	InsertRegion(ctx context.Context, arg InsertRegionParams) (int32, error)
	// Insert a new zman from snapshot (zman doesn't exist at all)
	InsertZmanFromSnapshot(ctx context.Context, arg InsertZmanFromSnapshotParams) error
	// Insert reference to existing tag for a request
	InsertZmanRequestExistingTag(ctx context.Context, arg InsertZmanRequestExistingTagParams) error
	// Insert new tag request for a zman request
	InsertZmanRequestNewTag(ctx context.Context, arg InsertZmanRequestNewTagParams) error
	// ============================================================================
	// Publisher Registration Tokens - SQLc Queries
	// Story 8-37: Unified Publisher Onboarding Flow
	// ============================================================================
	// =============================================================================
	// BLOCKED EMAILS
	// =============================================================================
	IsEmailBlocked(ctx context.Context, email string) (bool, error)
	// Create a linked publisher zman (from another publisher's zman)
	LinkPublisherZmanFromExample(ctx context.Context, arg LinkPublisherZmanFromExampleParams) (LinkPublisherZmanFromExampleRow, error)
	// Update the tag request to link the newly created tag
	// Must also clear requested_tag_name to satisfy tag_reference_check constraint
	LinkTagToRequest(ctx context.Context, arg LinkTagToRequestParams) error
	ListAllInvitationsByPublisher(ctx context.Context, publisherID int32) ([]ListAllInvitationsByPublisherRow, error)
	// List localities with search index hierarchy data
	// Uses geo_locality_resolved_coords view for best system-wide coordinates
	ListLocalities(ctx context.Context, arg ListLocalitiesParams) ([]ListLocalitiesRow, error)
	// ============================================
	// MASTER REGISTRY BROWSER (Story 11.1)
	// ============================================
	// List all master zmanim for the registry browser with filters, search, and import status
	// Parameters: publisher_id, categories (array), shitas (array), search, status, limit, offset
	ListMasterZmanimForRegistry(ctx context.Context, arg ListMasterZmanimForRegistryParams) ([]ListMasterZmanimForRegistryRow, error)
	ListPendingInvitationsByPublisher(ctx context.Context, publisherID int32) ([]ListPendingInvitationsByPublisherRow, error)
	ListPublisherSnapshots(ctx context.Context, publisherID int32) ([]ListPublisherSnapshotsRow, error)
	// List a publisher's zmanim with ownership check against current publisher
	// Returns whether the current publisher already has each master zman (active or deleted)
	ListPublisherZmanimForExamples(ctx context.Context, arg ListPublisherZmanimForExamplesParams) ([]ListPublisherZmanimForExamplesRow, error)
	// Fetches all published zmanim with master registry metadata and tags for report
	// @param publisher_id: The publisher ID
	// @param transliteration_style: 'ashkenazi' (default) or 'sephardi' - controls tag display names
	ListPublisherZmanimForReport(ctx context.Context, arg ListPublisherZmanimForReportParams) ([]ListPublisherZmanimForReportRow, error)
	ListPublishers(ctx context.Context, arg ListPublishersParams) ([]ListPublishersRow, error)
	ListPublishersByIDs(ctx context.Context, dollar_1 []string) ([]ListPublishersByIDsRow, error)
	// ============================================
	// PUBLISHER EXAMPLES BROWSER (Story 11.3)
	// ============================================
	// Get all verified/active publishers for the publisher examples browser
	ListValidatedPublishers(ctx context.Context) ([]ListValidatedPublishersRow, error)
	// ============================================================================
	// Legacy Service Queries (for publisher_service.go migration)
	// ============================================================================
	// Get verified/active publishers with pagination
	ListVerifiedPublishers(ctx context.Context, arg ListVerifiedPublishersParams) ([]ListVerifiedPublishersRow, error)
	ListVersionHistory(ctx context.Context, algorithmID int32) ([]ListVersionHistoryRow, error)
	// Rollback audit --
	LogRollback(ctx context.Context, arg LogRollbackParams) error
	MarkTokenCompleted(ctx context.Context, token string) error
	// =============================================================================
	// VERIFICATION FLOW
	// =============================================================================
	MarkTokenVerified(ctx context.Context, arg MarkTokenVerifiedParams) error
	// ============================================================================
	// Event Mapping Queries
	// ============================================================================
	// Get the best matching tag for a HebCal event using the PostgreSQL function
	// This wraps the match_hebcal_event() function for use with SQLc
	// Returns tag details including display names for matched events
	MatchHebcalEvent(ctx context.Context, arg MatchHebcalEventParams) ([]MatchHebcalEventRow, error)
	PermanentDeletePublisherZman(ctx context.Context, arg PermanentDeletePublisherZmanParams) error
	PermanentDeleteZman(ctx context.Context, arg PermanentDeleteZmanParams) error
	PublishAlgorithm(ctx context.Context, id int32) (pgtype.Timestamptz, error)
	// Bulk publish/unpublish zmanim --
	PublishAllZmanim(ctx context.Context, publisherID int32) error
	PublishZmanimByKeys(ctx context.Context, arg PublishZmanimByKeysParams) error
	// Checks if publisher has coverage for a specific locality
	PublisherHasCoverageForLocality(ctx context.Context, arg PublisherHasCoverageForLocalityParams) (bool, error)
	// File: actions.sql
	// Purpose: Action reification queries for provenance tracking
	// Pattern: action-reification
	// Complexity: low (single concept - provenance)
	// Used by: All services that create/update state
	// Records a new action in the actions table (starts with 'pending' status)
	// Returns the action_id for tracking
	RecordAction(ctx context.Context, arg RecordActionParams) (string, error)
	// Refresh the materialized view (call after updating geo data)
	RefreshGeoSearchIndex(ctx context.Context) error
	// Mark a publisher request as rejected
	RejectPublisherRequest(ctx context.Context, arg RejectPublisherRequestParams) error
	RejectRegistration(ctx context.Context, arg RejectRegistrationParams) error
	// Reject a new tag request by deleting it from zman_request_tags
	RejectTagRequest(ctx context.Context, id int32) error
	// Reject a zman request
	RejectZmanRequest(ctx context.Context, arg RejectZmanRequestParams) (RejectZmanRequestRow, error)
	// Remove a tag from a publisher zman
	RemoveTagFromPublisherZman(ctx context.Context, arg RemoveTagFromPublisherZmanParams) error
	ResendInvitationUpdateToken(ctx context.Context, arg ResendInvitationUpdateTokenParams) (PublisherInvitation, error)
	// Restore a soft-deleted zman that exists in snapshot being restored
	RestoreDeletedZmanForSnapshot(ctx context.Context, arg RestoreDeletedZmanForSnapshotParams) error
	RestorePublisherZman(ctx context.Context, arg RestorePublisherZmanParams) (RestorePublisherZmanRow, error)
	RestoreZman(ctx context.Context, arg RestoreZmanParams) (RestoreZmanRow, error)
	RevertCorrectionRequest(ctx context.Context, arg RevertCorrectionRequestParams) error
	// Reverts all publisher zman tags to match master registry state
	// Deletes all publisher-specific tags and resets to master defaults
	RevertPublisherZmanTags(ctx context.Context, publisherZmanID int32) error
	// Update request status during review
	ReviewZmanRegistryRequest(ctx context.Context, arg ReviewZmanRegistryRequestParams) (ReviewZmanRegistryRequestRow, error)
	// Update zman formula during rollback
	RollbackPublisherZmanFormula(ctx context.Context, arg RollbackPublisherZmanFormulaParams) (RollbackPublisherZmanFormulaRow, error)
	RollbackZmanToVersion(ctx context.Context, arg RollbackZmanToVersionParams) (RollbackZmanToVersionRow, error)
	// ============================================================================
	// DAILY ROLLUP QUERIES
	// These are used by background jobs to maintain the pre-aggregated table
	// ============================================================================
	// Aggregates raw logs into daily stats
	// Should be run daily via cron/scheduler
	RollupCalculationStatsDaily(ctx context.Context, dollar_1 pgtype.Date) error
	// Geo Names SQL Queries
	// Unified location search using geo_search_index table
	// ============================================================================
	// GEO_SEARCH_INDEX QUERIES (Denormalized Table - Ultra-Fast Search)
	// Target: <10ms response time via pre-computed denormalized data
	// ============================================================================
	// Exact search for context matching (countries/regions only)
	// Used by FindContextMatches to lookup country/region IDs by name/alias
	SearchGeoIndexExactContextOnly(ctx context.Context, arg SearchGeoIndexExactContextOnlyParams) ([]SearchGeoIndexExactContextOnlyRow, error)
	// ============================================
	// Localities Queries for Overture Geographic Data
	// Uses geo_search_index for denormalized hierarchy data
	// ============================================
	// Tiered search: exact keyword match -> fuzzy trigram -> population ranking
	// Uses geo_search_index which has resolved hierarchy via parent_overture_id
	// Generates search terms including individual words, consecutive pairs, and full phrase
	// e.g. "lakewood new jersey" -> ["lakewood", "new", "jersey", "lakewood new", "new jersey", "lakewood new jersey"]
	SearchLocalities(ctx context.Context, arg SearchLocalitiesParams) ([]SearchLocalitiesRow, error)
	// Search localities filtered to a publisher's coverage areas (hierarchy-aware)
	// Returns only localities that fall within the publisher's coverage:
	// - Direct locality coverage match
	// - Within a covered region (via ancestor_region_ids)
	// - Within a covered country
	// - Within a covered continent
	// Uses MATERIALIZED CTEs to force GIN index usage before coverage filtering
	// MATERIALIZED forces GIN index usage before coverage filter (critical for performance)
	// MATERIALIZED forces trigram index usage before coverage filter
	SearchLocalitiesWithPublisherCoverage(ctx context.Context, arg SearchLocalitiesWithPublisherCoverageParams) ([]SearchLocalitiesWithPublisherCoverageRow, error)
	SearchMasterZmanim(ctx context.Context, dollar_1 *string) ([]SearchMasterZmanimRow, error)
	SearchPublishersAll(ctx context.Context, arg SearchPublishersAllParams) ([]SearchPublishersAllRow, error)
	SearchPublishersWithAlgorithm(ctx context.Context, arg SearchPublishersWithAlgorithmParams) ([]SearchPublishersWithAlgorithmRow, error)
	// Search regions by name with locality counts
	// Uses geo_search_index.inherited_region_id for accurate locality counts
	SearchRegions(ctx context.Context, arg SearchRegionsParams) ([]SearchRegionsRow, error)
	SetAlgorithmVisibility(ctx context.Context, arg SetAlgorithmVisibilityParams) error
	// Replace all tags for a publisher zman (delete existing, insert new)
	// First delete all existing tags for the zman
	SetPublisherZmanTags(ctx context.Context, publisherZmanID int32) error
	// ============================================
	// SOFT DELETE QUERIES
	// ============================================
	SoftDeletePublisherZman(ctx context.Context, arg SoftDeletePublisherZmanParams) (SoftDeletePublisherZmanRow, error)
	// Soft delete a publisher zman (exec version)
	SoftDeletePublisherZmanExec(ctx context.Context, arg SoftDeletePublisherZmanExecParams) error
	// ============================================
	// SOFT DELETE QUERIES (ADDITIONAL)
	// ============================================
	SoftDeleteZman(ctx context.Context, arg SoftDeleteZmanParams) error
	// ============================================
	// SNAPSHOT RESTORE QUERIES
	// ============================================
	// Soft delete a zman that exists in current state but not in snapshot being restored
	SoftDeleteZmanForRestore(ctx context.Context, arg SoftDeleteZmanForRestoreParams) error
	// User SQL Queries
	// SQLc will generate type-safe Go code from these queries
	StorePasswordResetToken(ctx context.Context, arg StorePasswordResetTokenParams) error
	UnblockEmail(ctx context.Context, email string) error
	UnpublishAllZmanim(ctx context.Context, publisherID int32) error
	UnpublishZmanimByKeys(ctx context.Context, arg UnpublishZmanimByKeysParams) error
	// Update algorithm configuration --
	UpdateAlgorithmConfiguration(ctx context.Context, arg UpdateAlgorithmConfigurationParams) error
	UpdateAlgorithmDraft(ctx context.Context, arg UpdateAlgorithmDraftParams) (UpdateAlgorithmDraftRow, error)
	// Updates a pending correction request (publisher can only update their own pending requests)
	UpdateCorrectionRequest(ctx context.Context, arg UpdateCorrectionRequestParams) (LocationCorrectionRequest, error)
	UpdateCorrectionRequestStatus(ctx context.Context, arg UpdateCorrectionRequestStatusParams) error
	UpdateCoverageActive(ctx context.Context, arg UpdateCoverageActiveParams) (UpdateCoverageActiveRow, error)
	UpdateCoveragePriority(ctx context.Context, arg UpdateCoveragePriorityParams) (UpdateCoveragePriorityRow, error)
	UpdateInvitationStatus(ctx context.Context, arg UpdateInvitationStatusParams) (PublisherInvitation, error)
	UpdateInvitationToken(ctx context.Context, arg UpdateInvitationTokenParams) error
	UpdateLocalityElevationOverride(ctx context.Context, arg UpdateLocalityElevationOverrideParams) (GeoLocalityElevation, error)
	UpdateLocalityLocationOverride(ctx context.Context, arg UpdateLocalityLocationOverrideParams) (UpdateLocalityLocationOverrideRow, error)
	UpdateLocalityTimezone(ctx context.Context, arg UpdateLocalityTimezoneParams) error
	UpdatePublisherCalculationSettings(ctx context.Context, arg UpdatePublisherCalculationSettingsParams) (UpdatePublisherCalculationSettingsRow, error)
	// Update the is_global flag for a publisher
	UpdatePublisherIsGlobal(ctx context.Context, arg UpdatePublisherIsGlobalParams) (UpdatePublisherIsGlobalRow, error)
	UpdatePublisherLogo(ctx context.Context, arg UpdatePublisherLogoParams) (UpdatePublisherLogoRow, error)
	UpdatePublisherProfile(ctx context.Context, arg UpdatePublisherProfileParams) (UpdatePublisherProfileRow, error)
	UpdatePublisherProfileByClerkUserID(ctx context.Context, arg UpdatePublisherProfileByClerkUserIDParams) (UpdatePublisherProfileByClerkUserIDRow, error)
	// ============================================
	// PROFILE AND COVERAGE IMPORT
	// ============================================
	// Update publisher profile fields from import
	UpdatePublisherProfileFromImport(ctx context.Context, arg UpdatePublisherProfileFromImportParams) error
	UpdatePublisherStatus(ctx context.Context, arg UpdatePublisherStatusParams) (UpdatePublisherStatusRow, error)
	// Update publisher's preferred English transliteration style
	UpdatePublisherTransliterationStyle(ctx context.Context, arg UpdatePublisherTransliterationStyleParams) (UpdatePublisherTransliterationStyleRow, error)
	UpdatePublisherZman(ctx context.Context, arg UpdatePublisherZmanParams) (UpdatePublisherZmanRow, error)
	// Update an alias
	UpdatePublisherZmanAlias(ctx context.Context, arg UpdatePublisherZmanAliasParams) (UpdatePublisherZmanAliasRow, error)
	// ============================================================================
	// Import/Export Queries
	// ============================================================================
	// Update an existing publisher zman from import data
	UpdatePublisherZmanFromImport(ctx context.Context, arg UpdatePublisherZmanFromImportParams) error
	// =============================================================================
	// STATUS UPDATES (Legacy compatibility + new statuses)
	// =============================================================================
	UpdateRegistrationTokenStatus(ctx context.Context, arg UpdateRegistrationTokenStatusParams) error
	UpdateZmanCurrentVersion(ctx context.Context, arg UpdateZmanCurrentVersionParams) error
	// Update an existing zman with data from snapshot (creates new version via trigger)
	UpdateZmanFromSnapshot(ctx context.Context, arg UpdateZmanFromSnapshotParams) error
	UpdateZmanRegistryRequestStatus(ctx context.Context, arg UpdateZmanRegistryRequestStatusParams) (UpdateZmanRegistryRequestStatusRow, error)
	UpsertExplanationCache(ctx context.Context, arg UpsertExplanationCacheParams) error
	// Insert or update a zman during import (handles all fields including rounding_mode)
	UpsertPublisherZmanFromImport(ctx context.Context, arg UpsertPublisherZmanFromImportParams) (int32, error)
	UpsertPublisherZmanLegacy(ctx context.Context, arg UpsertPublisherZmanLegacyParams) error
	// Onboarding SQL Queries
	// Wizard trigger simplified: shows when zmanim count = 0
	// Publisher Zmanim Upserts for Wizard --
	UpsertPublisherZmanWithMaster(ctx context.Context, arg UpsertPublisherZmanWithMasterParams) error
	// Check if a zman key exists in the master registry
	ValidateMasterZmanKeyExists(ctx context.Context, zmanKey string) (bool, error)
	// Check if a key has a pending request
	ValidatePendingRequestKeyExists(ctx context.Context, requestedKey string) (bool, error)
}

var _ Querier = (*Queries)(nil)
