#!/bin/bash
set -e

# Shtetl Zmanim Development Environment Startup Script (Fast Version)
# This script handles runtime configuration only
# All dependencies are pre-installed in the Docker image

echo "🚀 Starting Shtetl Zmanim Development Environment..."

# Color codes for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Fix workspace directory ownership (needed for Docker volumes)
sudo chown -R coder:coder /home/coder/workspace

# Change to workspace directory
cd /home/coder/workspace/zmanim

# Step 1: Update repository to latest
print_status "Updating repository to latest..."
git fetch origin
CURRENT_BRANCH=$(git branch --show-current)
git reset --hard origin/${CURRENT_BRANCH} || print_warning "Failed to reset to origin/${CURRENT_BRANCH}"
print_success "Repository updated to latest ${CURRENT_BRANCH}"

# Step 2: Update dependencies if package files changed
print_status "Checking for dependency updates..."

# Update Go dependencies if needed
if git diff HEAD@{1} --name-only 2>/dev/null | grep -q "api/go.mod\|api/go.sum"; then
    print_status "Go dependencies changed, updating..."
    cd api && go mod download && cd ..
    print_success "Go dependencies updated"
fi

# Update Node dependencies if needed
if git diff HEAD@{1} --name-only 2>/dev/null | grep -q "web/package.*\.json"; then
    print_status "Node dependencies changed, updating..."
    cd web && npm ci && cd ..
    print_success "Node dependencies updated"
fi

# Step 3: Create .env files from Coder template variables
print_status "Setting up environment files from Coder variables..."

# Create api/.env from environment variables (set by Coder template)
if [ -n "$DATABASE_URL" ]; then
    cat > api/.env << ENVEOF
# Generated by Coder workspace startup

# Database & Cache (local Coder containers via Docker network)
DATABASE_URL=${DATABASE_URL}
REDIS_URL=${REDIS_URL}

# Authentication
CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
CLERK_JWKS_URL=${CLERK_JWKS_URL}
CLERK_ISSUER=${CLERK_ISSUER}

# Server Configuration
ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:3001,http://127.0.0.1:3000,http://127.0.0.1:3001,https://localhost:3000,https://localhost:3001,https://127.0.0.1:3000,https://127.0.0.1:3001}
PORT=8080
GO_ENV=development

# Email
RESEND_API_KEY=${RESEND_API_KEY}
RESEND_DOMAIN=${RESEND_DOMAIN}
RESEND_FROM=${RESEND_FROM}
ENVEOF
    print_success "api/.env created from Coder variables"
else
    print_warning "DATABASE_URL not set - copy .env.example to api/.env and configure"
    [ -f ".env.example" ] && [ ! -f "api/.env" ] && cp .env.example api/.env
fi

# Create web/.env.local from environment variables (set by Coder template)
if [ -n "$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY" ]; then
    cat > web/.env.local << ENVEOF
# Generated by Coder workspace startup

# Production Authentication
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
CLERK_JWKS_URL=${CLERK_JWKS_URL}

# Test Authentication (Clerk TEST instance)
CLERK_TEST_PUBLISHABLE_KEY=${CLERK_TEST_PUBLISHABLE_KEY:-}
CLERK_TEST_SECRET_KEY=${CLERK_TEST_SECRET_KEY:-}

# API & Database
NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://127.0.0.1:8080}
# Email
MAILSLURP_API_KEY=${MAILSLURP_API_KEY:-}
RESEND_API_KEY=${RESEND_API_KEY}
RESEND_DOMAIN=${RESEND_DOMAIN}
RESEND_FROM=${RESEND_FROM}
ENVEOF
    print_success "web/.env.local created from Coder variables"
else
    print_warning "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY not set - copy .env.example to web/.env.local and configure"
    [ -f ".env.example" ] && [ ! -f "web/.env.local" ] && cp .env.example web/.env.local
fi

# Create tests/.env for E2E testing with local database and cache
print_status "Setting up E2E test environment..."
if [ -n "$DATABASE_URL" ]; then
    cat > tests/.env << ENVEOF
# Generated by Coder workspace startup
# Application URL
BASE_URL=http://localhost:3001

# Clerk TEST Instance (for E2E tests)
CLERK_SECRET_KEY=${CLERK_TEST_SECRET_KEY:-${CLERK_SECRET_KEY}}
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${CLERK_TEST_PUBLISHABLE_KEY:-${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}}

# Database (local PostgreSQL via Docker network)
DATABASE_URL=${DATABASE_URL}

# Cache (local Redis via Docker network)
REDIS_URL=${REDIS_URL}

# MailSlurp Configuration (for email testing)
MAILSLURP_API_KEY=${MAILSLURP_API_KEY:-}

# Skip cleanup after tests (useful for debugging)
# SKIP_CLEANUP=true
ENVEOF
    print_success "tests/.env created with local database and cache"
else
    print_warning "DATABASE_URL not set - copy .env.example to tests/.env and configure"
    [ -f "tests/.env.example" ] && [ ! -f "tests/.env" ] && cp tests/.env.example tests/.env
fi

# Step 4: Copy API key env files from Coder secrets
print_status "Setting up API key environment files..."

# Clerk Authentication (required by push-template.sh)
if [ -n "$CLERK_SECRET_KEY" ]; then
    cat > .env.clerk << ENVEOF
# Clerk Authentication

# Production Instance
CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
CLERK_JWKS_URL=${CLERK_JWKS_URL}
CLERK_ISSUER=${CLERK_ISSUER}

# Test Instance (for E2E testing)
CLERK_TEST_SECRET_KEY=${CLERK_TEST_SECRET_KEY:-}
CLERK_TEST_PUBLISHABLE_KEY=${CLERK_TEST_PUBLISHABLE_KEY:-}
ENVEOF
    print_success ".env.clerk created from Coder variables"
else
    print_warning "CLERK_SECRET_KEY not set - copy .env.clerk.example to .env.clerk and configure"
    [ -f ".env.clerk.example" ] && [ ! -f ".env.clerk" ] && cp .env.clerk.example .env.clerk
fi

# Resend Email Service (required by push-template.sh)
if [ -n "$RESEND_API_KEY" ]; then
    cat > .env.resend << ENVEOF
# Resend Email Service

RESEND_API_KEY=${RESEND_API_KEY}
RESEND_DOMAIN=${RESEND_DOMAIN}
RESEND_FROM=${RESEND_FROM}
ENVEOF
    print_success ".env.resend created from Coder variables"
else
    print_warning "RESEND_API_KEY not set - copy .env.resend.example to .env.resend and configure"
    [ -f ".env.resend.example" ] && [ ! -f ".env.resend" ] && cp .env.resend.example .env.resend
fi

# MailSlurp Email Testing (required by push-template.sh)
if [ -n "$MAILSLURP_API_KEY" ]; then
    cat > .env.mailslurp << ENVEOF
# MailSlurp Email Testing

MAILSLURP_API_KEY=${MAILSLURP_API_KEY}
ENVEOF
    print_success ".env.mailslurp created from Coder variables"
else
    print_warning "MAILSLURP_API_KEY not set - copy .env.mailslurp.example to .env.mailslurp and configure"
    [ -f ".env.mailslurp.example" ] && [ ! -f ".env.mailslurp" ] && cp .env.mailslurp.example .env.mailslurp
fi

# OpenAI API Key (for RAG embeddings)
if [ -n "$OPENAI_API_KEY" ]; then
    cat > .env.openai << ENVEOF
# OpenAI API Key
# Used for: RAG embeddings (text-embedding-3-small) in Epic 4

OPENAI_API_KEY=${OPENAI_API_KEY}
ENVEOF
    print_success ".env.openai created from Coder variables"
else
    print_warning "OPENAI_API_KEY not set - copy .env.openai.example to .env.openai and configure"
    [ -f ".env.openai.example" ] && [ ! -f ".env.openai" ] && cp .env.openai.example .env.openai
fi

# Anthropic/Claude API Key (for AI formula generation)
if [ -n "$ANTHROPIC_API_KEY" ]; then
    cat > .env.claude << ENVEOF
# Anthropic API Key (Claude)
# Used for: AI formula generation and explanations in Epic 4

ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
ENVEOF
    print_success ".env.claude created from Coder variables"
else
    print_warning "ANTHROPIC_API_KEY not set - copy .env.claude.example to .env.claude and configure"
    [ -f ".env.claude.example" ] && [ ! -f ".env.claude" ] && cp .env.claude.example .env.claude
fi

# Step 5: Configure git user identity (with Coder variable overrides)
print_status "Configuring git user identity..."
GIT_USER_NAME="${GIT_USER_NAME:-Daniel Niasoff}"
GIT_USER_EMAIL="${GIT_USER_EMAIL:-4070285+dniasoff@users.noreply.github.com}"

git config --global user.name "$GIT_USER_NAME"
git config --global user.email "$GIT_USER_EMAIL"
print_success "Git user configured: $GIT_USER_NAME <$GIT_USER_EMAIL>"

# Step 6: Display status
echo ""
echo "=========================================="
echo "✅ Shtetl Zmanim Development Environment Ready!"
echo "=========================================="
echo ""
echo "📦 Pre-installed (in Docker image):"
echo "  - Go $(go version 2>/dev/null | awk '{print $3}' || echo 'not found')"
echo "  - sqlc $(sqlc version 2>/dev/null || echo 'not found')"
echo "  - Node.js $(node --version 2>/dev/null || echo 'not found')"
echo "  - npm $(npm --version 2>/dev/null || echo 'not found')"
echo "  - Jest $(jest --version 2>/dev/null || echo 'not found')"
echo "  - Claude Code $(claude --version 2>/dev/null || echo 'not found')"
echo "  - Fly.io CLI $(flyctl version 2>/dev/null | head -n1 || echo 'not found')"
echo "  - uv $(uv --version 2>/dev/null || echo 'not found')"
echo "  - Playwright (Chromium)"
echo ""
echo "🔧 Configuration:"
echo "  - Git User: $(git config --global user.name 2>/dev/null || echo 'not configured')"
echo "  - Git Email: $(git config --global user.email 2>/dev/null || echo 'not configured')"
echo "  - Branch: $(git branch --show-current)"
echo ""
echo "🛠️  Services (local Coder containers):"
echo "  - PostgreSQL: postgres:5432"
echo "  - Redis: redis:6379"
echo "  - Clerk: ${CLERK_TEST_SECRET_KEY:+TEST instance}${CLERK_TEST_SECRET_KEY:-using LIVE instance}"
echo "  - Email: Resend"
echo ""

# Step 7: Run database migrations
print_status "Running database migrations..."
if [ -f "scripts/migrate.sh" ]; then
    chmod +x scripts/migrate.sh
    ./scripts/migrate.sh || print_warning "Migration failed - database may need manual setup"
    print_success "Database migrations complete"
else
    print_warning "migrate.sh not found - run migrations manually"
fi

# Step 8: Auto-start services
print_status "Starting services in background..."
if [ -f ".coder/start-services.sh" ]; then
    chmod +x .coder/start-services.sh
    ./.coder/start-services.sh --no-attach
    print_success "Services started in tmux session 'zmanim'"
    echo ""
    echo "🎯 Services are now running!"
    echo "   - Attach to tmux: tmux attach -t zmanim"
    echo "   - View API logs: tmux select-window -t zmanim:api"
    echo "   - View Web logs: tmux select-window -t zmanim:web"
    echo ""
    echo "📋 Service URLs:"
    echo "   - Web App: http://localhost:3001"
    echo "   - Go API: http://localhost:8080"
    echo ""
else
    print_warning "start-services.sh not found - start services manually"
fi

echo "=========================================="
print_success "Startup complete! 🎉"
echo "=========================================="
